/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/public/v1/announcements': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Active Announcements
		 * @description Retrieve active announcements sorted by newest first, paginated.
		 */
		get: operations['get_active_announcements_public_v1_announcements_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/api-keys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Api Keys */
		get: operations['list_api_keys_v1_admin_api_keys_get'];
		put?: never;
		/** Create Api Key */
		post: operations['create_api_key_v1_admin_api_keys_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/api-keys/{key_id}/revoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revoke Api Key */
		post: operations['revoke_api_key_v1_admin_api_keys__key_id__revoke_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Verify Auth
		 * @description Verify connectivity using EXTERNAL_API_SECRET Bearer token.
		 */
		get: operations['verify_auth_v1_auth_verify_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/config/faqs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Faqs
		 * @description Get public FAQs from the MongoDB read model.
		 */
		get: operations['get_faqs_public_v1_config_faqs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Donation */
		post: operations['create_donation_public_v1_donations_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations/track-search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Track Search Donation
		 * @description Resolve booking_ref (DN-…) + phone → tracking_token (CR-052 §2.6).
		 */
		post: operations['track_search_donation_public_v1_donations_track_search_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations/{tracking_token}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Donation */
		get: operations['get_donation_public_v1_donations__tracking_token__get'];
		put?: never;
		post?: never;
		/**
		 * Cancel Donation
		 * @description Cancel on the Mongo intake buffer (pre-inbound only).
		 */
		delete: operations['cancel_donation_public_v1_donations__tracking_token__delete'];
		options?: never;
		head?: never;
		/**
		 * Patch Donation Courier
		 * @description Update courier tracking on the Mongo intake buffer (pre-inbound only).
		 */
		patch: operations['patch_donation_courier_public_v1_donations__tracking_token__patch'];
		trace?: never;
	};
	'/public/v1/donations/{tracking_token}/items': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Patch Donation Items
		 * @description Donor edits their own declared items, moving the quota by the difference (CR-080).
		 *
		 *     A separate path from the courier PATCH above: that one touches only the intake
		 *     buffer and can never be refused, while this one moves the atomic counter and answers
		 *     409 when the target is full.
		 */
		patch: operations['patch_donation_items_public_v1_donations__tracking_token__items_patch'];
		trace?: never;
	};
	'/public/v1/occupants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Search Evacuees
		 * @description Search evacuees in the public read model (masked, no PII leakage).
		 */
		post: operations['search_evacuees_public_v1_occupants_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/shelters': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * ดึงรายการศูนย์พักพิง (get-list-shelter)
		 * @description ดึงรายการศูนย์พักพิงสำหรับระบบภายนอก (M2).
		 */
		get: operations['list_shelters_external_v1_shelters_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/persons/shelter-residency': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * ตรวจสอบสถานะการเข้าพัก (get-person-shelter-residency)
		 * @description ตรวจสอบสถานะการเข้าพักศูนย์พักพิงของผู้ประสบภัยจากเลขประจำตัวประชาชน (CID).
		 */
		get: operations['get_person_shelter_residency_external_v1_persons_shelter_residency_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/shelters/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Shelter */
		get: operations['get_shelter_external_v1_shelters__code__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/needs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Needs */
		get: operations['list_needs_external_v1_needs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/occupants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Search Evacuees */
		post: operations['search_evacuees_external_v1_occupants_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/announcements': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Active Announcements */
		get: operations['get_active_announcements_external_v1_announcements_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/config/faqs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Faqs */
		get: operations['get_faqs_external_v1_config_faqs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint to verify the service is running.
		 *     Returns a simple message indicating the service is healthy.
		 */
		get: operations['health_check_v1_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/needs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Needs */
		get: operations['list_needs_public_v1_needs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/shelters': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Shelters
		 * @description List shelters from the MongoDB read model.
		 */
		get: operations['list_shelters_public_v1_shelters_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/shelters/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Shelter
		 * @description Get shelter detail from the MongoDB read model.
		 */
		get: operations['get_shelter_public_v1_shelters__code__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/transparency/summary': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Transparency Summary
		 * @description System-wide public metrics from public_shelters + public_persons.
		 */
		get: operations['get_transparency_summary_public_v1_transparency_summary_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Jobs */
		get: operations['list_jobs_public_v1_jobs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/jobs/{job_id}/apply': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Apply To Job */
		post: operations['apply_to_job_public_v1_jobs__job_id__apply_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/volunteer/ticket/{token}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Ticket */
		get: operations['get_ticket_public_v1_volunteer_ticket__token__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/volunteer/ticket/find': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Find Tickets */
		post: operations['find_tickets_public_v1_volunteer_ticket_find_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/volunteer/ticket/{token}/cancel': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Cancel Ticket */
		post: operations['cancel_ticket_public_v1_volunteer_ticket__token__cancel_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/volunteer/schedule': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Volunteer Schedule
		 * @description ตารางทำงานจิตอาสา — the roster behind the Access Portal (CR-092 หน้าจอ 6).
		 */
		post: operations['volunteer_schedule_public_v1_volunteer_schedule_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/volunteer/schedule/respond': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Respond To Dispatch
		 * @description Accept or decline an offered shift with the code a manager read out.
		 */
		post: operations['respond_to_dispatch_public_v1_volunteer_schedule_respond_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** ApiErrorBody */
		ApiErrorBody: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** ApiErrorResponse */
		ApiErrorResponse: {
			error: components['schemas']['ApiErrorBody'];
		};
		/** ApiKeyCreateRequest */
		ApiKeyCreateRequest: {
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/**
			 * Created By
			 * @description SA Couch username who issues the key
			 */
			created_by: string;
		};
		/**
		 * ApiKeyCreateResponse
		 * @description Create response — plaintext ``api_key`` is returned once.
		 */
		ApiKeyCreateResponse: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/** Created By */
			created_by: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Revoked At */
			revoked_at?: string | null;
			/** Last Used At */
			last_used_at?: string | null;
			/** Api Key */
			api_key: string;
		};
		/** ApiKeyListResponse */
		ApiKeyListResponse: {
			/** Keys */
			keys: components['schemas']['ApiKeyPublic'][];
			/** Count */
			count: number;
		};
		/**
		 * ApiKeyPublic
		 * @description Key metadata without secret material.
		 */
		ApiKeyPublic: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/** Created By */
			created_by: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Revoked At */
			revoked_at?: string | null;
			/** Last Used At */
			last_used_at?: string | null;
		};
		/** ApiKeyRevokeResponse */
		ApiKeyRevokeResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			key: components['schemas']['ApiKeyPublic'];
		};
		/** ConfigResponse */
		ConfigResponse: {
			/**
			 * Faqs
			 * @default []
			 */
			faqs: components['schemas']['FaqItem'][];
			/** Line Oa Url */
			line_oa_url?: string | null;
			/** Facebook Url */
			facebook_url?: string | null;
			/** Phone Number */
			phone_number?: string | null;
		};
		/**
		 * DispatchRespondRequest
		 * @description Answering an offered shift — two factors, neither enough alone.
		 *
		 *     ``phone`` is what the portal signed in with and must match the assignment;
		 *     ``code`` is the short code a manager read out. A six-character code is only safe
		 *     because the caller has to know whose shift it is as well.
		 */
		DispatchRespondRequest: {
			/** Assignment Id */
			assignment_id: string;
			/** Phone */
			phone: string;
			/** Code */
			code: string;
			/**
			 * Action
			 * @enum {string}
			 */
			action: 'accepted' | 'declined';
		};
		/** DispatchRespondResponse */
		DispatchRespondResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Assignment Id */
			assignment_id: string;
			/** Dispatch Status */
			dispatch_status: string;
		};
		/** DonationCancelResponse */
		DonationCancelResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Donation cancelled successfully
			 */
			message: string;
		};
		/** DonationCourierPatchRequest */
		DonationCourierPatchRequest: {
			/** Courier Tracking No */
			courier_tracking_no: string;
		};
		/** DonationCourierPatchResponse */
		DonationCourierPatchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Courier tracking number updated
			 */
			message: string;
		};
		/** DonationCreateRequest */
		DonationCreateRequest: {
			/** Shelter Code */
			shelter_code: string;
			/** Campaign Id */
			campaign_id?: string | null;
			donor: components['schemas']['DonorInput'];
			/** Items */
			items?: components['schemas']['DonationItemInput'][];
			/** Logistics */
			logistics?: {
				[key: string]: unknown;
			} | null;
			/** Captchatoken */
			captchaToken?: string | null;
		};
		/** DonationCreateResponse */
		DonationCreateResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Booking Ref */
			booking_ref: string;
		};
		/** DonationItemInput */
		DonationItemInput: {
			/** Item Id */
			item_id?: string | null;
			/** Category */
			category?: string | null;
			/** Free Text */
			free_text?: string | null;
			/** Qty */
			qty: string | number;
			/** Unit */
			unit?: string | null;
			/** Condition */
			condition?: string | null;
			/** Note */
			note?: string | null;
		};
		/** DonationItemsPatchRequest */
		DonationItemsPatchRequest: {
			/** Items */
			items: components['schemas']['DonationItemInput'][];
		};
		/** DonationItemsPatchResponse */
		DonationItemsPatchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Donation items updated
			 */
			message: string;
			/**
			 * Revisions
			 * @default 0
			 */
			revisions: number;
			/** Items */
			items?: {
				[key: string]: unknown;
			}[];
			/** Revision */
			revision?: {
				[key: string]: unknown;
			};
		};
		/**
		 * DonationTrackSearchRequest
		 * @description CR-052 §2.6 — human booking_ref + phone exact match (not token alone).
		 */
		DonationTrackSearchRequest: {
			/** Booking Ref */
			booking_ref: string;
			/** Phone */
			phone: string;
		};
		/** DonationTrackSearchResponse */
		DonationTrackSearchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Booking Ref */
			booking_ref: string;
		};
		/** DonationTrackingResponse */
		DonationTrackingResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Donation */
			donation: {
				[key: string]: unknown;
			};
		};
		/** DonorInput */
		DonorInput: {
			/** Name */
			name: string;
			/** Phone */
			phone: string;
			/** Line Id */
			line_id?: string | null;
			/** Email */
			email?: string | null;
		};
		/** FamilyMember */
		FamilyMember: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** Shelter Name */
			shelter_name: string;
		};
		/** FaqItem */
		FaqItem: {
			/** Id */
			id?: string | null;
			/** Question */
			question: string;
			/** Answer */
			answer: string;
			/** Question En */
			question_en?: string | null;
			/** Answer En */
			answer_en?: string | null;
			/**
			 * Is Published
			 * @default true
			 */
			is_published: boolean;
			/**
			 * Order
			 * @default 0
			 */
			order: number;
		};
		/** GeoJsonPoint */
		GeoJsonPoint: {
			/**
			 * Type
			 * @default Point
			 */
			type: string;
			/** Coordinates */
			coordinates: number[];
		};
		/** GeoPoint */
		GeoPoint: {
			/** Lat */
			lat: number;
			/** Lng */
			lng: number;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Errors */
			errors?: components['schemas']['ValidationError'][];
		};
		/** HealthCheckResponse */
		HealthCheckResponse: {
			/** Status */
			status: string;
		};
		/** JobShiftTemplate */
		JobShiftTemplate: {
			/**
			 * Shift Name
			 * @default
			 */
			shift_name: string;
			/**
			 * Start Time
			 * @default
			 */
			start_time: string;
			/**
			 * End Time
			 * @default
			 */
			end_time: string;
			/** Days */
			days?: string[];
		};
		/** M2ErrorDetail */
		M2ErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** M2ErrorResponse */
		M2ErrorResponse: {
			error: components['schemas']['M2ErrorDetail'];
		};
		/** M2PersonResidencyResponse */
		M2PersonResidencyResponse: {
			/**
			 * Shelter Id
			 * @description รหัสศูนย์พักพิง
			 */
			shelter_id: string;
			/**
			 * Shelter Name
			 * @description ชื่อศูนย์พักพิง
			 */
			shelter_name: string;
			/**
			 * Checkin Datetime
			 * @description วันเวลาที่เช็คอิน (ISO 8601 พร้อม timezone เช่น 2026-08-20T14:30:00+07:00)
			 */
			checkin_datetime: string;
			/**
			 * Status
			 * @description สถานะการเข้าพัก
			 * @enum {string}
			 */
			status: 'CHECKED_IN' | 'CHECKED_OUT';
		};
		/** M2ShelterItem */
		M2ShelterItem: {
			/**
			 * Shelter Id
			 * @description รหัสศูนย์พักพิง เช่น SH001
			 */
			shelter_id: string;
			/**
			 * Shelter Name
			 * @description ชื่อศูนย์พักพิง
			 */
			shelter_name: string;
			/**
			 * Site Kind
			 * @description ชนิดสถานที่
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/**
			 * Lat
			 * @description พิกัดละติจูด (WGS 84)
			 */
			lat?: number | null;
			/**
			 * Long
			 * @description พิกัดลองจิจูด (WGS 84)
			 */
			long?: number | null;
		};
		/** NeedItemResponse */
		NeedItemResponse: {
			/** Item Id */
			item_id: string;
			/** Name */
			name: string;
			/** Qty Needed */
			qty_needed: string;
			/** Unit */
			unit: string;
			/** Status */
			status: string;
		};
		/** NeedsListResponse */
		NeedsListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterNeedsResponse'][];
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** PaginatedAnnouncements */
		PaginatedAnnouncements: {
			/** Items */
			items: components['schemas']['PublicAnnouncement'][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Size */
			size: number;
			/** Total Pages */
			total_pages: number;
		};
		/**
		 * PublicAnnouncement
		 * @description Public snapshot of a system announcement, stored in MongoDB `public_announcements`.
		 *     Sourced from `announcement` docs in CouchDB `registry`.
		 */
		PublicAnnouncement: {
			/**
			 * Id
			 * @description The CouchDB announcement document ID
			 */
			_id: string;
			/** Title */
			title: string;
			/** Description */
			description: string;
			/** Title En */
			title_en?: string | null;
			/** Description En */
			description_en?: string | null;
			/**
			 * Severity
			 * @enum {string}
			 */
			severity: 'info' | 'warning' | 'emergency';
			/** Is Active */
			is_active: boolean;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/**
		 * PublicJobItem
		 * @description One card on the board (CR-092 screen 1).
		 *
		 *     Carries the 2-colour quota the card renders (``รับแล้ว`` / ``ว่าง``) — the third,
		 *     ``dispatched``, is a back-office state and is folded into "not available" here
		 *     rather than shown to the public.
		 */
		PublicJobItem: {
			/** Job Id */
			job_id: string;
			/** Shelter Code */
			shelter_code: string;
			/**
			 * Shelter Name
			 * @default
			 */
			shelter_name: string;
			/** Title */
			title: string;
			/** Description */
			description: string;
			/** Tier */
			tier: string;
			/** Skills Required */
			skills_required?: string[];
			shift_template?: components['schemas']['JobShiftTemplate'];
			/** Quota */
			quota: number;
			/** Slots Confirmed */
			slots_confirmed: number;
			/** Slots Remaining */
			slots_remaining: number;
			/** Status */
			status: string;
			/**
			 * Requires Review
			 * @default false
			 */
			requires_review: boolean;
		};
		/** PublicJobListResponse */
		PublicJobListResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Jobs */
			jobs?: components['schemas']['PublicJobItem'][];
		};
		/**
		 * ScheduleLookupRequest
		 * @description Same key as the ticket lookup — the portal signs in by phone.
		 */
		ScheduleLookupRequest: {
			/** Phone */
			phone: string;
		};
		/**
		 * ScheduleShift
		 * @description One shift the volunteer is actually on (schema.md §2.9, CR-092 หน้าจอ 6).
		 *
		 *     Distinct from a ticket: a ticket is the application they filed, this is the roster
		 *     entry a manager put them on, with the duty window the Time-Bound access guard reads
		 *     and the check-in stamps the tablet station writes.
		 */
		ScheduleShift: {
			/** Assignment Id */
			assignment_id: string;
			/** Job Id */
			job_id: string;
			/**
			 * Job Title
			 * @default
			 */
			job_title: string;
			/** Shelter Code */
			shelter_code: string;
			/**
			 * Shelter Name
			 * @default
			 */
			shelter_name: string;
			/**
			 * Date
			 * @default
			 */
			date: string;
			/**
			 * Shift
			 * @default
			 */
			shift: string;
			/**
			 * Station
			 * @default
			 */
			station: string;
			/** Start Ts */
			start_ts?: string | null;
			/** End Ts */
			end_ts?: string | null;
			/** Check In At */
			check_in_at?: string | null;
			/** Check Out At */
			check_out_at?: string | null;
			/** Status */
			status: string;
			/** Dispatch Status */
			dispatch_status?: string | null;
		};
		/** SearchRequest */
		SearchRequest: {
			/** Search */
			search: string;
		};
		/** SearchResponse */
		SearchResponse: {
			/** Results */
			results: components['schemas']['SearchResult'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** SearchResult */
		SearchResult: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** National Id */
			national_id?: string | null;
			/** Gender */
			gender?: string | null;
			/** Shelter Name */
			shelter_name: string;
			/** Origin Address */
			origin_address?: string | null;
			/** Checked In At */
			checked_in_at?: string | null;
			/** Care Zone */
			care_zone?: string | null;
			/** Family Members */
			family_members?: components['schemas']['FamilyMember'][];
		};
		/** ShelterAdmissionPolicyDetail */
		ShelterAdmissionPolicyDetail: {
			/** Pets */
			pets: string;
			/** Vulnerable Groups */
			vulnerable_groups: string[];
		};
		/** ShelterCapacityDetail */
		ShelterCapacityDetail: {
			/** Total */
			total: number;
			/** Available */
			available: number;
		};
		/** ShelterContactDetail */
		ShelterContactDetail: {
			/** Manager */
			manager: string;
			/** Phone */
			phone: string;
		};
		/** ShelterDetail */
		ShelterDetail: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/**
			 * Site Kind
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/** Status */
			status: string;
			/** Admin Type */
			admin_type: string;
			/** Address */
			address: string;
			capacity: components['schemas']['ShelterCapacityDetail'];
			/** Occupancy Rate */
			occupancy_rate: number;
			/** Building Status */
			building_status: string;
			geo?: components['schemas']['GeoPoint'] | null;
			location?: components['schemas']['GeoJsonPoint'] | null;
			admission_policy: components['schemas']['ShelterAdmissionPolicyDetail'];
			travel: components['schemas']['ShelterTravelDetail'];
			facilities: components['schemas']['ShelterFacilitiesDetail'];
			/** Zones */
			zones?: components['schemas']['ShelterZoneDetail'][] | null;
			contact: components['schemas']['ShelterContactDetail'];
			/** Faq */
			faq: components['schemas']['ShelterFaqDetail'][];
		};
		/** ShelterDetailResponse */
		ShelterDetailResponse: {
			shelter: components['schemas']['ShelterDetail'];
		};
		/** ShelterFacilitiesDetail */
		ShelterFacilitiesDetail: {
			hygiene: components['schemas']['ShelterHygieneDetail'];
			/** Power */
			power: string;
			/** Water */
			water: string;
			/** Comms */
			comms: string[];
			/** Kitchen */
			kitchen: string;
			/** Parking */
			parking: string;
		};
		/** ShelterFaqDetail */
		ShelterFaqDetail: {
			/** Q */
			q: string;
			/** A */
			a: string;
		};
		/** ShelterHygieneDetail */
		ShelterHygieneDetail: {
			/** Male */
			male: number;
			/** Female */
			female: number;
			/** Accessible */
			accessible: number;
			/** Shower */
			shower: number;
			/** Mobile Toilet */
			mobile_toilet: number;
		};
		/** ShelterItem */
		ShelterItem: {
			/**
			 * Code
			 * @description Shelter code, e.g. SH001
			 */
			code: string;
			/** Name */
			name: string;
			/**
			 * Site Kind
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/** Status */
			status: string;
			/**
			 * Capacity
			 * @default 0
			 */
			capacity: number;
			geo?: components['schemas']['GeoPoint'] | null;
			location?: components['schemas']['GeoJsonPoint'] | null;
			/** Province */
			province?: string | null;
			/** District */
			district?: string | null;
			/** Subdistrict */
			subdistrict?: string | null;
			/** Pet Policy */
			pet_policy?: string | null;
			/** Vulnerable Groups */
			vulnerable_groups?: string[] | null;
			/** Admin Type */
			admin_type?: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ShelterListResponse */
		ShelterListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterItem'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** ShelterNeedsResponse */
		ShelterNeedsResponse: {
			/** Code */
			code: string;
			/** Name */
			name: string;
			/** Needs */
			needs: components['schemas']['NeedItemResponse'][];
		};
		/** ShelterTravelDetail */
		ShelterTravelDetail: {
			/** Route */
			route: string;
			/** Altitude */
			altitude: string;
			/** Flood Warning */
			flood_warning?: string | null;
		};
		/** ShelterZoneDetail */
		ShelterZoneDetail: {
			/** Name */
			name?: string | null;
			/** Type */
			type: string;
			/** Capacity */
			capacity?: number | null;
			/** Area M2 */
			area_m2?: number | null;
		};
		/** TicketFindItem */
		TicketFindItem: {
			/** View Token */
			view_token: string;
			/**
			 * Applicant Name
			 * @default
			 */
			applicant_name: string;
			/** Status */
			status: string;
			/**
			 * Job Title
			 * @default
			 */
			job_title: string;
			/** Shelter Code */
			shelter_code: string;
			/**
			 * Shift Date
			 * @default
			 */
			shift_date: string;
		};
		/**
		 * TicketFindRequest
		 * @description Tab 2 — "ค้นหาตั๋วของฉัน" by the phone the application was made with.
		 */
		TicketFindRequest: {
			/** Phone */
			phone: string;
		};
		/** TicketFindResponse */
		TicketFindResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tickets */
			tickets?: components['schemas']['TicketFindItem'][];
		};
		/** TicketShift */
		TicketShift: {
			/**
			 * Date
			 * @default
			 */
			date: string;
			/**
			 * Start Time
			 * @default
			 */
			start_time: string;
			/**
			 * End Time
			 * @default
			 */
			end_time: string;
			/** Station */
			station?: string | null;
		};
		/** TransparencySummary */
		TransparencySummary: {
			/** Shelters Total */
			shelters_total: number;
			/**
			 * Shelters Open
			 * @description status in {open, full}
			 */
			shelters_open: number;
			/**
			 * Occupancy Total
			 * @description active + pre_registered across projected shelters (CR-070)
			 */
			occupancy_total?: number | null;
			/**
			 * Vulnerable Count
			 * @description Not projected in public_persons yet — always null until schema adds age
			 */
			vulnerable_count?: number | null;
		};
		/** TransparencySummaryResponse */
		TransparencySummaryResponse: {
			summary: components['schemas']['TransparencySummary'];
			/**
			 * Last Updated
			 * Format: date-time
			 */
			last_updated: string;
			/**
			 * Is Stale
			 * @default false
			 */
			is_stale: boolean;
			/** Flags */
			flags?: {
				[key: string]: boolean;
			};
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** VerifyResponse */
		VerifyResponse: {
			/**
			 * Status
			 * @default ok
			 */
			status: string;
		};
		/**
		 * VolunteerApplyRequest
		 * @description The 4-field quick-apply form (FR-VOL-02.2).
		 *
		 *     ``national_id`` is optional here even though CR-092 lists it as a main field: a
		 *     volunteer with a passport or a pink card has no 13-digit number, and refusing them
		 *     at the form would be a worse failure than a profile that dedupes on phone alone.
		 */
		VolunteerApplyRequest: {
			/** First Name */
			first_name: string;
			/** Last Name */
			last_name: string;
			/** Phone */
			phone: string;
			/** National Id */
			national_id?: string | null;
			/** Email */
			email?: string | null;
			/** Skills */
			skills?: string[];
			/** Shift Date */
			shift_date?: string | null;
			/** Station */
			station?: string | null;
		};
		/** VolunteerApplyResponse */
		VolunteerApplyResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Status */
			status: string;
			/** Job Id */
			job_id: string;
		};
		/** VolunteerCancelResponse */
		VolunteerCancelResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Application cancelled
			 */
			message: string;
		};
		/** VolunteerScheduleResponse */
		VolunteerScheduleResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Shifts */
			shifts?: components['schemas']['ScheduleShift'][];
		};
		/**
		 * VolunteerTicket
		 * @description What the Digital Pass may show.
		 *
		 *     No ``national_id`` in any form and no raw phone — FR-VOL-03.4. ``token`` is echoed
		 *     because the pass displays it as the human-readable ticket id.
		 */
		VolunteerTicket: {
			/** Token */
			token: string;
			/**
			 * Can Cancel
			 * @default true
			 */
			can_cancel: boolean;
			/** Status */
			status: string;
			/** Job Id */
			job_id: string;
			/**
			 * Job Title
			 * @default
			 */
			job_title: string;
			/** Shelter Code */
			shelter_code: string;
			/**
			 * Shelter Name
			 * @default
			 */
			shelter_name: string;
			/** Applicant Name */
			applicant_name: string;
			/** Phone Masked */
			phone_masked: string;
			/** Skills */
			skills?: string[];
			selected_shift?: components['schemas']['TicketShift'];
			/** Applied At */
			applied_at: string;
			/** Qr Payload */
			qr_payload: string;
		};
		/** VolunteerTicketResponse */
		VolunteerTicketResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			ticket: components['schemas']['VolunteerTicket'];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_active_announcements_public_v1_announcements_get: {
		parameters: {
			query?: {
				/** @description Page number */
				page?: number;
				/** @description Items per page */
				size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedAnnouncements'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_api_keys_v1_admin_api_keys_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyListResponse'];
				};
			};
		};
	};
	create_api_key_v1_admin_api_keys_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ApiKeyCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	revoke_api_key_v1_admin_api_keys__key_id__revoke_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				key_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyRevokeResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	verify_auth_v1_auth_verify_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VerifyResponse'];
				};
			};
		};
	};
	get_faqs_public_v1_config_faqs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConfigResponse'];
				};
			};
		};
	};
	create_donation_public_v1_donations_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	track_search_donation_public_v1_donations_track_search_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationTrackSearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationTrackSearchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_donation_public_v1_donations__tracking_token__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationTrackingResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	cancel_donation_public_v1_donations__tracking_token__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCancelResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_donation_courier_public_v1_donations__tracking_token__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCourierPatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCourierPatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_donation_items_public_v1_donations__tracking_token__items_patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationItemsPatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationItemsPatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_evacuees_public_v1_occupants_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
			/** @description Too Many Requests */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
		};
	};
	list_shelters_external_v1_shelters_get: {
		parameters: {
			query?: {
				/** @description กรองสถานะ เช่น open */
				status?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ShelterItem'][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
		};
	};
	get_person_shelter_residency_external_v1_persons_shelter_residency_get: {
		parameters: {
			query: {
				/** @description เลขประจำตัวประชาชน 13 หลัก */
				cid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2PersonResidencyResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
		};
	};
	get_shelter_external_v1_shelters__code__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterDetailResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_needs_external_v1_needs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NeedsListResponse'];
				};
			};
		};
	};
	search_evacuees_external_v1_occupants_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
			/** @description Too Many Requests */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
		};
	};
	get_active_announcements_external_v1_announcements_get: {
		parameters: {
			query?: {
				/** @description Page number */
				page?: number;
				/** @description Items per page */
				size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedAnnouncements'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_faqs_external_v1_config_faqs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConfigResponse'];
				};
			};
		};
	};
	health_check_v1_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthCheckResponse'];
				};
			};
		};
	};
	list_needs_public_v1_needs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NeedsListResponse'];
				};
			};
		};
	};
	list_shelters_public_v1_shelters_get: {
		parameters: {
			query?: {
				province?: string | null;
				district?: string | null;
				subdistrict?: string | null;
				status?: string | null;
				site_kind?: ('evacuation_center' | 'host_house') | null;
				/** @description User latitude */
				lat?: number | null;
				/** @description User longitude */
				lng?: number | null;
				/** @description Search radius in kilometers */
				radius_km?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_shelter_public_v1_shelters__code__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterDetailResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_transparency_summary_public_v1_transparency_summary_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TransparencySummaryResponse'];
				};
			};
		};
	};
	list_jobs_public_v1_jobs_get: {
		parameters: {
			query?: {
				shelter_code?: string | null;
				skill?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PublicJobListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	apply_to_job_public_v1_jobs__job_id__apply_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				job_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['VolunteerApplyRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VolunteerApplyResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_ticket_public_v1_volunteer_ticket__token__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VolunteerTicketResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	find_tickets_public_v1_volunteer_ticket_find_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['TicketFindRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TicketFindResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	cancel_ticket_public_v1_volunteer_ticket__token__cancel_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VolunteerCancelResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	volunteer_schedule_public_v1_volunteer_schedule_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ScheduleLookupRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VolunteerScheduleResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	respond_to_dispatch_public_v1_volunteer_schedule_respond_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DispatchRespondRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DispatchRespondResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
