/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/public/v1/announcements': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Active Announcements
		 * @description Retrieve active announcements sorted by newest first, paginated.
		 */
		get: operations['get_active_announcements_public_v1_announcements_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/api-keys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Api Keys */
		get: operations['list_api_keys_v1_admin_api_keys_get'];
		put?: never;
		/** Create Api Key */
		post: operations['create_api_key_v1_admin_api_keys_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/api-keys/{key_id}/revoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revoke Api Key */
		post: operations['revoke_api_key_v1_admin_api_keys__key_id__revoke_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Verify Auth
		 * @description Verify connectivity using EXTERNAL_API_SECRET Bearer token.
		 */
		get: operations['verify_auth_v1_auth_verify_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/config/faqs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Faqs
		 * @description Get public FAQs from the MongoDB read model.
		 */
		get: operations['get_faqs_public_v1_config_faqs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Donation */
		post: operations['create_donation_public_v1_donations_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations/track-search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Track Search Donation
		 * @description Resolve booking_ref (DN-…) + phone → tracking_token (CR-052 §2.6).
		 */
		post: operations['track_search_donation_public_v1_donations_track_search_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations/{tracking_token}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Donation */
		get: operations['get_donation_public_v1_donations__tracking_token__get'];
		put?: never;
		post?: never;
		/**
		 * Cancel Donation
		 * @description Cancel on the Mongo intake buffer (pre-inbound only).
		 */
		delete: operations['cancel_donation_public_v1_donations__tracking_token__delete'];
		options?: never;
		head?: never;
		/**
		 * Patch Donation Courier
		 * @description Update courier tracking on the Mongo intake buffer (pre-inbound only).
		 */
		patch: operations['patch_donation_courier_public_v1_donations__tracking_token__patch'];
		trace?: never;
	};
	'/public/v1/donations/{tracking_token}/items': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Patch Donation Items
		 * @description Donor edits their own declared items, moving the quota by the difference (CR-080).
		 *
		 *     A separate path from the courier PATCH above: that one touches only the intake
		 *     buffer and can never be refused, while this one moves the atomic counter and answers
		 *     409 when the target is full.
		 */
		patch: operations['patch_donation_items_public_v1_donations__tracking_token__items_patch'];
		trace?: never;
	};
	'/public/v1/occupants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Search Evacuees
		 * @description Search evacuees in the public read model (masked, no PII leakage).
		 */
		post: operations['search_evacuees_public_v1_occupants_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/shelters': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * ดึงรายการศูนย์พักพิง (get-list-shelter)
		 * @description ดึงรายการศูนย์พักพิงสำหรับระบบภายนอก (M2).
		 */
		get: operations['list_shelters_external_v1_shelters_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/persons/shelter-residency': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * ตรวจสอบสถานะการเข้าพัก (get-person-shelter-residency)
		 * @description ตรวจสอบสถานะการเข้าพักศูนย์พักพิงของผู้ประสบภัยจากเลขประจำตัวประชาชน (CID).
		 */
		get: operations['get_person_shelter_residency_external_v1_persons_shelter_residency_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/shelters/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Shelter */
		get: operations['get_shelter_external_v1_shelters__code__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/needs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Needs */
		get: operations['list_needs_external_v1_needs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/occupants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Search Evacuees */
		post: operations['search_evacuees_external_v1_occupants_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/announcements': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Active Announcements */
		get: operations['get_active_announcements_external_v1_announcements_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/external/v1/config/faqs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Faqs */
		get: operations['get_faqs_external_v1_config_faqs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint to verify the service is running.
		 *     Returns a simple message indicating the service is healthy.
		 */
		get: operations['health_check_v1_health_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/needs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Needs */
		get: operations['list_needs_public_v1_needs_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/shelters': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Shelters
		 * @description List shelters from the MongoDB read model.
		 */
		get: operations['list_shelters_public_v1_shelters_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/shelters/{code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Shelter
		 * @description Get shelter detail from the MongoDB read model.
		 */
		get: operations['get_shelter_public_v1_shelters__code__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/token-third-party': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Issue Token */
		post: operations['issue_token_api_auth_token_third_party_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/thirdparty-clients': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Clients */
		get: operations['list_clients_v1_admin_thirdparty_clients_get'];
		put?: never;
		/** Create Client */
		post: operations['create_client_v1_admin_thirdparty_clients_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/admin/thirdparty-clients/{client_row_id}/revoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Revoke Client */
		post: operations['revoke_client_v1_admin_thirdparty_clients__client_row_id__revoke_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/locations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Locations */
		get: operations['list_locations_api_thirdparty_locations_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/locations/{location_code}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Location */
		get: operations['get_location_api_thirdparty_locations__location_code__get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/locations/{location_code}/occupancy': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Location Occupancy */
		get: operations['get_location_occupancy_api_thirdparty_locations__location_code__occupancy_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/locations/{location_code}/occupants': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Location Occupants */
		get: operations['get_location_occupants_api_thirdparty_locations__location_code__occupants_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/locations/{location_code}/stock': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Location Stock */
		get: operations['get_location_stock_api_thirdparty_locations__location_code__stock_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/thirdparty/summary': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Summary */
		get: operations['get_summary_api_thirdparty_summary_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/transparency/summary': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Transparency Summary
		 * @description System-wide public metrics from public_shelters + public_persons.
		 */
		get: operations['get_transparency_summary_public_v1_transparency_summary_get'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/unassigned-registrations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create Unassigned Registration
		 * @description Public pre-registration without a shelter — writes Mongo only (FR-UR-01).
		 */
		post: operations['create_unassigned_registration_public_v1_unassigned_registrations_post'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** ApiErrorBody */
		ApiErrorBody: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** ApiErrorResponse */
		ApiErrorResponse: {
			error: components['schemas']['ApiErrorBody'];
		};
		/** ApiKeyCreateRequest */
		ApiKeyCreateRequest: {
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/**
			 * Created By
			 * @description SA Couch username who issues the key
			 */
			created_by: string;
		};
		/**
		 * ApiKeyCreateResponse
		 * @description Create response — plaintext ``api_key`` is returned once.
		 */
		ApiKeyCreateResponse: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/** Created By */
			created_by: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Revoked At */
			revoked_at?: string | null;
			/** Last Used At */
			last_used_at?: string | null;
			/** Api Key */
			api_key: string;
		};
		/** ApiKeyListResponse */
		ApiKeyListResponse: {
			/** Keys */
			keys: components['schemas']['ApiKeyPublic'][];
			/** Count */
			count: number;
		};
		/**
		 * ApiKeyPublic
		 * @description Key metadata without secret material.
		 */
		ApiKeyPublic: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/** Owner */
			owner: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
			/** Created By */
			created_by: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Revoked At */
			revoked_at?: string | null;
			/** Last Used At */
			last_used_at?: string | null;
		};
		/** ApiKeyRevokeResponse */
		ApiKeyRevokeResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			key: components['schemas']['ApiKeyPublic'];
		};
		/** ConfigResponse */
		ConfigResponse: {
			/**
			 * Faqs
			 * @default []
			 */
			faqs: components['schemas']['FaqItem'][];
			/** Line Oa Url */
			line_oa_url?: string | null;
			/** Facebook Url */
			facebook_url?: string | null;
			/** Phone Number */
			phone_number?: string | null;
		};
		/** CriticalItem */
		CriticalItem: {
			/** Name Th */
			name_th: string;
			/** Quantity On Hand */
			quantity_on_hand: number;
			/** Unit Label */
			unit_label: string;
			/** Level */
			level: string;
		};
		/** DonationCancelResponse */
		DonationCancelResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Donation cancelled successfully
			 */
			message: string;
		};
		/** DonationCourierPatchRequest */
		DonationCourierPatchRequest: {
			/** Courier Tracking No */
			courier_tracking_no: string;
		};
		/** DonationCourierPatchResponse */
		DonationCourierPatchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Courier tracking number updated
			 */
			message: string;
		};
		/** DonationCreateRequest */
		DonationCreateRequest: {
			/** Shelter Code */
			shelter_code: string;
			/** Campaign Id */
			campaign_id?: string | null;
			donor: components['schemas']['DonorInput'];
			/** Items */
			items?: components['schemas']['DonationItemInput'][];
			/** Logistics */
			logistics?: {
				[key: string]: unknown;
			} | null;
			/** Captchatoken */
			captchaToken?: string | null;
		};
		/** DonationCreateResponse */
		DonationCreateResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Booking Ref */
			booking_ref: string;
		};
		/** DonationItemInput */
		DonationItemInput: {
			/** Item Id */
			item_id?: string | null;
			/** Category */
			category?: string | null;
			/** Free Text */
			free_text?: string | null;
			/** Qty */
			qty: string | number;
			/** Unit */
			unit?: string | null;
			/** Condition */
			condition?: string | null;
			/** Note */
			note?: string | null;
		};
		/** DonationItemsPatchRequest */
		DonationItemsPatchRequest: {
			/** Items */
			items: components['schemas']['DonationItemInput'][];
		};
		/** DonationItemsPatchResponse */
		DonationItemsPatchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Donation items updated
			 */
			message: string;
			/**
			 * Revisions
			 * @default 0
			 */
			revisions: number;
			/** Items */
			items?: {
				[key: string]: unknown;
			}[];
			/** Revision */
			revision?: {
				[key: string]: unknown;
			};
		};
		/**
		 * DonationTrackSearchRequest
		 * @description CR-052 §2.6 — human booking_ref + phone exact match (not token alone).
		 */
		DonationTrackSearchRequest: {
			/** Booking Ref */
			booking_ref: string;
			/** Phone */
			phone: string;
		};
		/** DonationTrackSearchResponse */
		DonationTrackSearchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Booking Ref */
			booking_ref: string;
		};
		/** DonationTrackingResponse */
		DonationTrackingResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Donation */
			donation: {
				[key: string]: unknown;
			};
		};
		/** DonorInput */
		DonorInput: {
			/** Name */
			name: string;
			/** Phone */
			phone: string;
			/** Line Id */
			line_id?: string | null;
			/** Email */
			email?: string | null;
		};
		/** FamilyMember */
		FamilyMember: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** Shelter Name */
			shelter_name: string;
		};
		/** FaqItem */
		FaqItem: {
			/** Id */
			id?: string | null;
			/** Question */
			question: string;
			/** Answer */
			answer: string;
			/** Question En */
			question_en?: string | null;
			/** Answer En */
			answer_en?: string | null;
			/**
			 * Is Published
			 * @default true
			 */
			is_published: boolean;
			/**
			 * Order
			 * @default 0
			 */
			order: number;
		};
		/** GeoJsonPoint */
		GeoJsonPoint: {
			/**
			 * Type
			 * @default Point
			 */
			type: string;
			/** Coordinates */
			coordinates: number[];
		};
		/** GeoPoint */
		GeoPoint: {
			/** Lat */
			lat: number;
			/** Lng */
			lng: number;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Errors */
			errors?: components['schemas']['ValidationError'][];
		};
		/** HealthCheckResponse */
		HealthCheckResponse: {
			/** Status */
			status: string;
		};
		/** HouseholdInput */
		HouseholdInput: {
			/** Housing Type */
			housing_type?:
				('owned_house' | 'rented_house' | 'condo' | 'apartment_dorm' | 'homeless') | null;
			/** Residence Landmark */
			residence_landmark?: string | null;
			/** Address No */
			address_no?: string | null;
			/** Village No */
			village_no?: string | null;
			/** Subdistrict */
			subdistrict?: string | null;
			/** District */
			district?: string | null;
			/** Province */
			province?: string | null;
			/** Postal Code */
			postal_code?: string | null;
			/** Geo */
			geo?: {
				[key: string]: unknown;
			} | null;
			/** Pets */
			pets?: components['schemas']['PetInput'][];
			/** Label */
			label?: string | null;
		};
		/** LocationDetailEnvelope */
		LocationDetailEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			result: components['schemas']['LocationDetailItem'];
		};
		/** LocationDetailItem */
		LocationDetailItem: {
			/** Location Code */
			location_code: string;
			/** Name Th */
			name_th: string;
			/** Name Short */
			name_short: string | null;
			/** Location Type */
			location_type: string;
			/** Location Subtype */
			location_subtype: string | null;
			/** Location Status */
			location_status: string;
			/** Latitude */
			latitude: number | null;
			/** Longitude */
			longitude: number | null;
			/** Address */
			address: string | null;
			/** Subdistrict Code */
			subdistrict_code: string | null;
			/** District Code */
			district_code: string | null;
			/** Province Code */
			province_code: string | null;
			/** Capacity */
			capacity: number;
			/** Contact Phone */
			contact_phone: string | null;
			/** Contact Name */
			contact_name: string | null;
			/** Operating Org */
			operating_org: string | null;
			/** Accepts Delivery */
			accepts_delivery: boolean;
			/** Delivery Note */
			delivery_note: string | null;
			/** Opened At */
			opened_at: string | null;
			/** Closed At */
			closed_at: string | null;
			/** Is Active */
			is_active: boolean;
			/** Occupancy Total */
			occupancy_total: number;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Facilities */
			facilities: string[];
		};
		/** LocationErrorDetail */
		LocationErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** LocationErrorResponse */
		LocationErrorResponse: {
			error: components['schemas']['LocationErrorDetail'];
		};
		/** LocationItem */
		LocationItem: {
			/** Location Code */
			location_code: string;
			/** Name Th */
			name_th: string;
			/** Name Short */
			name_short: string | null;
			/** Location Type */
			location_type: string;
			/** Location Subtype */
			location_subtype: string | null;
			/** Location Status */
			location_status: string;
			/** Latitude */
			latitude: number | null;
			/** Longitude */
			longitude: number | null;
			/** Address */
			address: string | null;
			/** Subdistrict Code */
			subdistrict_code: string | null;
			/** District Code */
			district_code: string | null;
			/** Province Code */
			province_code: string | null;
			/** Capacity */
			capacity: number;
			/** Contact Phone */
			contact_phone: string | null;
			/** Contact Name */
			contact_name: string | null;
			/** Operating Org */
			operating_org: string | null;
			/** Accepts Delivery */
			accepts_delivery: boolean;
			/** Delivery Note */
			delivery_note: string | null;
			/** Opened At */
			opened_at: string | null;
			/** Closed At */
			closed_at: string | null;
			/** Is Active */
			is_active: boolean;
			/** Occupancy Total */
			occupancy_total: number;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** LocationListEnvelope */
		LocationListEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			/** Result */
			result: components['schemas']['LocationItem'][];
		};
		/** LocationOccupancyEnvelope */
		LocationOccupancyEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			result: components['schemas']['LocationOccupancyResult'];
		};
		/** LocationOccupancyResult */
		LocationOccupancyResult: {
			/** Location Code */
			location_code: string;
			/** Capacity */
			capacity: number;
			/** Occupancy Total */
			occupancy_total: number;
			breakdown: components['schemas']['OccupancyBreakdownItem'];
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Updated By Role */
			updated_by_role: string;
		};
		/** LocationStockEnvelope */
		LocationStockEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			result: components['schemas']['LocationStockResult'];
		};
		/** LocationStockResult */
		LocationStockResult: {
			/** Location Code */
			location_code: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Items */
			items: components['schemas']['StockItem'][];
		};
		/** M2ErrorDetail */
		M2ErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** M2ErrorResponse */
		M2ErrorResponse: {
			error: components['schemas']['M2ErrorDetail'];
		};
		/** M2PersonResidencyResponse */
		M2PersonResidencyResponse: {
			/**
			 * Shelter Id
			 * @description รหัสศูนย์พักพิง
			 */
			shelter_id: string;
			/**
			 * Shelter Name
			 * @description ชื่อศูนย์พักพิง
			 */
			shelter_name: string;
			/**
			 * Checkin Datetime
			 * @description วันเวลาที่เช็คอิน (ISO 8601 พร้อม timezone เช่น 2026-08-20T14:30:00+07:00)
			 */
			checkin_datetime: string;
			/**
			 * Status
			 * @description สถานะการเข้าพัก
			 * @enum {string}
			 */
			status: 'CHECKED_IN' | 'CHECKED_OUT';
			/**
			 * Stay Status
			 * @description สถานะ stay ดิบจาก projection (CR-112 additive)
			 */
			stay_status: string;
			/**
			 * In Zone
			 * @description True เมื่อยืนยันถึงโซนแล้ว (room_confirmed)
			 */
			in_zone: boolean;
		};
		/** M2ShelterItem */
		M2ShelterItem: {
			/**
			 * Shelter Id
			 * @description รหัสศูนย์พักพิง เช่น SH001
			 */
			shelter_id: string;
			/**
			 * Shelter Name
			 * @description ชื่อศูนย์พักพิง
			 */
			shelter_name: string;
			/**
			 * Site Kind
			 * @description ชนิดสถานที่
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/**
			 * Lat
			 * @description พิกัดละติจูด (WGS 84)
			 */
			lat?: number | null;
			/**
			 * Long
			 * @description พิกัดลองจิจูด (WGS 84)
			 */
			long?: number | null;
		};
		/** MemberCreated */
		MemberCreated: {
			/** Reserved Evacuee Id */
			reserved_evacuee_id: string;
			/**
			 * Status
			 * @enum {string}
			 */
			status: 'open' | 'claimed' | 'cancelled';
			/** First Name */
			first_name: string;
			/** Last Name */
			last_name: string;
			/** Gender */
			gender: string;
			/** Phone */
			phone?: string | null;
			person_id?: components['schemas']['PersonIdInput'] | null;
			/** Country */
			country: string;
			/** Vulnerable Groups */
			vulnerable_groups?: string[];
			/** Special Needs */
			special_needs?: string[];
		};
		/** MemberInput */
		MemberInput: {
			/** First Name */
			first_name: string;
			/**
			 * Last Name
			 * @default
			 */
			last_name: string;
			/**
			 * Gender
			 * @enum {string}
			 */
			gender: 'male' | 'female' | 'other';
			/** Phone */
			phone?: string | null;
			person_id?: components['schemas']['PersonIdInput'] | null;
			/**
			 * Country
			 * @default THAILAND
			 */
			country: string;
			/** Vulnerable Groups */
			vulnerable_groups?: string[];
			/** Special Needs */
			special_needs?: string[];
			/** Birth Year */
			birth_year?: number | null;
			/** Age */
			age?: number | null;
			/** Nickname */
			nickname?: string | null;
			/** Religion */
			religion?: string | null;
		};
		/** NeedItemResponse */
		NeedItemResponse: {
			/** Item Id */
			item_id: string;
			/** Name */
			name: string;
			/** Qty Needed */
			qty_needed: string;
			/** Unit */
			unit: string;
			/** Status */
			status: string;
		};
		/** NeedsListResponse */
		NeedsListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterNeedsResponse'][];
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** OccupancyBreakdownItem */
		OccupancyBreakdownItem: {
			/** Male */
			male: number;
			/** Female */
			female: number;
			/** Child Under 5 */
			child_under_5: number;
			/** Elderly Over 60 */
			elderly_over_60: number;
			/** Pregnant */
			pregnant: number;
			/** Bedridden */
			bedridden: number;
			/** Disabled */
			disabled: number;
		};
		/** OccupancyErrorDetail */
		OccupancyErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** OccupancyErrorResponse */
		OccupancyErrorResponse: {
			error: components['schemas']['OccupancyErrorDetail'];
		};
		/** OccupantItem */
		OccupantItem: {
			/** Occupant Ref */
			occupant_ref: string;
			/** Name Masked */
			name_masked: string;
			/** Age Range */
			age_range: string;
			/** Gender */
			gender?: string | null;
			/**
			 * Care Flags
			 * @default []
			 */
			care_flags: string[];
			/** Checked In At */
			checked_in_at?: string | null;
		};
		/** OccupantsEnvelope */
		OccupantsEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			/**
			 * Result
			 * @default []
			 */
			result: components['schemas']['OccupantItem'][];
		};
		/** OccupantsErrorResponse */
		OccupantsErrorResponse: {
			/** Status */
			status: number;
			/** Message */
			message: string;
			/** Detail */
			detail?: string | null;
		};
		/** PaginatedAnnouncements */
		PaginatedAnnouncements: {
			/** Items */
			items: components['schemas']['PublicAnnouncement'][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Size */
			size: number;
			/** Total Pages */
			total_pages: number;
		};
		/** PersonIdInput */
		PersonIdInput: {
			/**
			 * Cardtype
			 * @default national_id
			 * @enum {string}
			 */
			cardType: 'national_id' | 'passport' | 'pink_card' | 'other' | 'anonymous';
			/** Number */
			number?: string | null;
		};
		/** PetInput */
		PetInput: {
			/**
			 * Species
			 * @enum {string}
			 */
			species: 'dog' | 'cat' | 'other';
			/**
			 * Count
			 * @default 1
			 */
			count: number;
			/** Notes */
			notes?: string | null;
			/**
			 * Has Cage
			 * @default false
			 */
			has_cage: boolean;
		};
		/**
		 * PublicAnnouncement
		 * @description Public snapshot of a system announcement, stored in MongoDB `public_announcements`.
		 *     Sourced from `announcement` docs in CouchDB `registry`.
		 */
		PublicAnnouncement: {
			/**
			 * Id
			 * @description The CouchDB announcement document ID
			 */
			_id: string;
			/** Title */
			title: string;
			/** Description */
			description: string;
			/** Title En */
			title_en?: string | null;
			/** Description En */
			description_en?: string | null;
			/**
			 * Severity
			 * @enum {string}
			 */
			severity: 'info' | 'warning' | 'emergency';
			/** Is Active */
			is_active: boolean;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** SearchRequest */
		SearchRequest: {
			/** Search */
			search: string;
		};
		/** SearchResponse */
		SearchResponse: {
			/** Results */
			results: components['schemas']['SearchResult'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** SearchResult */
		SearchResult: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** National Id */
			national_id?: string | null;
			/** Gender */
			gender?: string | null;
			/** Shelter Name */
			shelter_name: string;
			/** Origin Address */
			origin_address?: string | null;
			/** Checked In At */
			checked_in_at?: string | null;
			/** Care Zone */
			care_zone?: string | null;
			/** Family Members */
			family_members?: components['schemas']['FamilyMember'][];
		};
		/** ShelterAdmissionPolicyDetail */
		ShelterAdmissionPolicyDetail: {
			/** Pets */
			pets: string;
			/** Vulnerable Groups */
			vulnerable_groups: string[];
		};
		/** ShelterCapacityDetail */
		ShelterCapacityDetail: {
			/** Total */
			total: number;
			/** Available */
			available: number;
		};
		/** ShelterContactDetail */
		ShelterContactDetail: {
			/** Manager */
			manager: string;
			/** Phone */
			phone: string;
		};
		/** ShelterDetail */
		ShelterDetail: {
			/** Id */
			id: string;
			/** Name */
			name: string;
			/**
			 * Site Kind
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/** Status */
			status: string;
			/** Admin Type */
			admin_type: string;
			/** Address */
			address: string;
			capacity: components['schemas']['ShelterCapacityDetail'];
			/**
			 * Occupancy
			 * @description Forecast Occupancy headcount
			 */
			occupancy: number;
			/**
			 * Present
			 * @description Present Occupancy headcount
			 */
			present: number;
			/**
			 * In Zone
			 * @description In-zone Occupancy headcount (room_confirmed)
			 */
			in_zone: number;
			/** Occupancy Rate */
			occupancy_rate: number;
			/** Building Status */
			building_status: string;
			geo?: components['schemas']['GeoPoint'] | null;
			location?: components['schemas']['GeoJsonPoint'] | null;
			admission_policy: components['schemas']['ShelterAdmissionPolicyDetail'];
			travel: components['schemas']['ShelterTravelDetail'];
			facilities: components['schemas']['ShelterFacilitiesDetail'];
			/** Zones */
			zones?: components['schemas']['ShelterZoneDetail'][] | null;
			contact: components['schemas']['ShelterContactDetail'];
			/** Faq */
			faq: components['schemas']['ShelterFaqDetail'][];
		};
		/** ShelterDetailResponse */
		ShelterDetailResponse: {
			shelter: components['schemas']['ShelterDetail'];
		};
		/** ShelterFacilitiesDetail */
		ShelterFacilitiesDetail: {
			hygiene: components['schemas']['ShelterHygieneDetail'];
			/** Power */
			power: string;
			/** Water */
			water: string;
			/** Comms */
			comms: string[];
			/** Kitchen */
			kitchen: string;
			/** Parking */
			parking: string;
		};
		/** ShelterFaqDetail */
		ShelterFaqDetail: {
			/** Q */
			q: string;
			/** A */
			a: string;
		};
		/** ShelterHygieneDetail */
		ShelterHygieneDetail: {
			/** Male */
			male: number;
			/** Female */
			female: number;
			/** Accessible */
			accessible: number;
			/** Shower */
			shower: number;
			/** Mobile Toilet */
			mobile_toilet: number;
		};
		/** ShelterItem */
		ShelterItem: {
			/**
			 * Code
			 * @description Shelter code, e.g. SH001
			 */
			code: string;
			/** Name */
			name: string;
			/**
			 * Site Kind
			 * @default evacuation_center
			 * @enum {string}
			 */
			site_kind: 'evacuation_center' | 'host_house';
			/** Status */
			status: string;
			/**
			 * Capacity
			 * @default 0
			 */
			capacity: number;
			geo?: components['schemas']['GeoPoint'] | null;
			location?: components['schemas']['GeoJsonPoint'] | null;
			/** Province */
			province?: string | null;
			/** District */
			district?: string | null;
			/** Subdistrict */
			subdistrict?: string | null;
			/** Pet Policy */
			pet_policy?: string | null;
			/** Vulnerable Groups */
			vulnerable_groups?: string[] | null;
			/** Admin Type */
			admin_type?: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ShelterListResponse */
		ShelterListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterItem'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** ShelterNeedsResponse */
		ShelterNeedsResponse: {
			/** Code */
			code: string;
			/** Name */
			name: string;
			/** Needs */
			needs: components['schemas']['NeedItemResponse'][];
		};
		/** ShelterTravelDetail */
		ShelterTravelDetail: {
			/** Route */
			route: string;
			/** Altitude */
			altitude: string;
			/** Flood Warning */
			flood_warning?: string | null;
		};
		/** ShelterZoneDetail */
		ShelterZoneDetail: {
			/** Name */
			name?: string | null;
			/** Type */
			type: string;
			/** Capacity */
			capacity?: number | null;
			/** Area M2 */
			area_m2?: number | null;
		};
		/** StockErrorDetail */
		StockErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** StockErrorResponse */
		StockErrorResponse: {
			error: components['schemas']['StockErrorDetail'];
		};
		/** StockItem */
		StockItem: {
			/** M6 Reference Id */
			m6_reference_id: number | null;
			/** M6 Item Code */
			m6_item_code: string | null;
			/** Name Th */
			name_th: string;
			/** Type Code */
			type_code: string;
			/** Unit Label */
			unit_label: string;
			/** Unit Ratio */
			unit_ratio: number;
			/** Quantity On Hand */
			quantity_on_hand: number;
			/** Source */
			source: string;
		};
		/** SummaryEnvelope */
		SummaryEnvelope: {
			/**
			 * Status
			 * @default 200
			 */
			status: number;
			/**
			 * Message
			 * @default Found Data.
			 */
			message: string;
			result: components['schemas']['SummaryResult'];
		};
		/** SummaryLocationItem */
		SummaryLocationItem: {
			/** Location Code */
			location_code: string;
			/** Name Th */
			name_th: string;
			/** Location Status */
			location_status: string;
			/** Latitude */
			latitude: number | null;
			/** Longitude */
			longitude: number | null;
			/** Capacity */
			capacity: number;
			/** Occupancy Total */
			occupancy_total: number;
			/** Critical Items */
			critical_items: components['schemas']['CriticalItem'][];
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** SummaryResult */
		SummaryResult: {
			/**
			 * Generated At
			 * Format: date-time
			 */
			generated_at: string;
			/** Location Count */
			location_count: number;
			/** Occupancy Total */
			occupancy_total?: number | null;
			/** Capacity Total */
			capacity_total: number;
			/** Locations */
			locations: components['schemas']['SummaryLocationItem'][];
		};
		/** ThirdPartyClientCreateRequest */
		ThirdPartyClientCreateRequest: {
			/** Client Id */
			client_id: string;
			/** Module Name */
			module_name: string;
			/** Allowed Scopes */
			allowed_scopes: string[];
		};
		/**
		 * ThirdPartyClientCreateResponse
		 * @description Create response — plaintext ``client_secret`` is returned once.
		 */
		ThirdPartyClientCreateResponse: {
			/** Id */
			id: string;
			/** Client Id */
			client_id: string;
			/** Module Name */
			module_name: string;
			/** Allowed Scopes */
			allowed_scopes: string[];
			/** Is Active */
			is_active: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Client Secret */
			client_secret: string;
		};
		/** ThirdPartyClientListResponse */
		ThirdPartyClientListResponse: {
			/** Clients */
			clients: components['schemas']['ThirdPartyClientPublic'][];
			/** Count */
			count: number;
		};
		/**
		 * ThirdPartyClientPublic
		 * @description Client metadata without the secret hash.
		 */
		ThirdPartyClientPublic: {
			/** Id */
			id: string;
			/** Client Id */
			client_id: string;
			/** Module Name */
			module_name: string;
			/** Allowed Scopes */
			allowed_scopes: string[];
			/** Is Active */
			is_active: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ThirdPartyClientRevokeResponse */
		ThirdPartyClientRevokeResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			client: components['schemas']['ThirdPartyClientPublic'];
		};
		/** TokenErrorDetail */
		TokenErrorDetail: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** TokenErrorResponse */
		TokenErrorResponse: {
			error: components['schemas']['TokenErrorDetail'];
		};
		/** TokenRequest */
		TokenRequest: {
			/** Grant Type */
			grant_type: string;
			/** Client Id */
			client_id: string;
			/** Client Secret */
			client_secret: string;
		};
		/** TokenResponse */
		TokenResponse: {
			/** Access Token */
			access_token: string;
			/**
			 * Token Type
			 * @default Bearer
			 * @constant
			 */
			token_type: 'Bearer';
			/** Expires In */
			expires_in: number;
			/** Module Name */
			module_name: string;
			/** Scopes */
			scopes: string[];
		};
		/** TransparencySummary */
		TransparencySummary: {
			/** Shelters Total */
			shelters_total: number;
			/**
			 * Shelters Open
			 * @description status in {open, full}
			 */
			shelters_open: number;
			/**
			 * Occupancy Total
			 * @description active + pre_registered across projected shelters (CR-070)
			 */
			occupancy_total?: number | null;
			/**
			 * Vulnerable Count
			 * @description Not projected in public_persons yet — always null until schema adds age
			 */
			vulnerable_count?: number | null;
		};
		/** TransparencySummaryResponse */
		TransparencySummaryResponse: {
			summary: components['schemas']['TransparencySummary'];
			/**
			 * Last Updated
			 * Format: date-time
			 */
			last_updated: string;
			/**
			 * Is Stale
			 * @default false
			 */
			is_stale: boolean;
			/** Flags */
			flags?: {
				[key: string]: boolean;
			};
		};
		/** UnassignedRegistrationCreateRequest */
		UnassignedRegistrationCreateRequest: {
			/** Members */
			members: components['schemas']['MemberInput'][];
			household: components['schemas']['HouseholdInput'];
			/**
			 * Registered Via
			 * @default web
			 * @enum {string}
			 */
			registered_via: 'web' | 'staff';
		};
		/** UnassignedRegistrationCreateResponse */
		UnassignedRegistrationCreateResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Id */
			id: string;
			/** Schema V */
			schema_v: number;
			/** Reserved Household Id */
			reserved_household_id: string;
			/** Members */
			members: components['schemas']['MemberCreated'][];
			/**
			 * Registered Via
			 * @enum {string}
			 */
			registered_via: 'web' | 'staff';
			/** Status */
			status: string;
			/** Created At */
			created_at: string;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** VerifyResponse */
		VerifyResponse: {
			/**
			 * Status
			 * @default ok
			 */
			status: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	get_active_announcements_public_v1_announcements_get: {
		parameters: {
			query?: {
				/** @description Page number */
				page?: number;
				/** @description Items per page */
				size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedAnnouncements'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_api_keys_v1_admin_api_keys_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyListResponse'];
				};
			};
		};
	};
	create_api_key_v1_admin_api_keys_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ApiKeyCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	revoke_api_key_v1_admin_api_keys__key_id__revoke_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				key_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiKeyRevokeResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	verify_auth_v1_auth_verify_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VerifyResponse'];
				};
			};
		};
	};
	get_faqs_public_v1_config_faqs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConfigResponse'];
				};
			};
		};
	};
	create_donation_public_v1_donations_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	track_search_donation_public_v1_donations_track_search_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationTrackSearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationTrackSearchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_donation_public_v1_donations__tracking_token__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationTrackingResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	cancel_donation_public_v1_donations__tracking_token__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCancelResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_donation_courier_public_v1_donations__tracking_token__patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCourierPatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCourierPatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_donation_items_public_v1_donations__tracking_token__items_patch: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationItemsPatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationItemsPatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_evacuees_public_v1_occupants_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
			/** @description Too Many Requests */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
		};
	};
	list_shelters_external_v1_shelters_get: {
		parameters: {
			query?: {
				/** @description กรองสถานะ เช่น open */
				status?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ShelterItem'][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
		};
	};
	get_person_shelter_residency_external_v1_persons_shelter_residency_get: {
		parameters: {
			query: {
				/** @description เลขประจำตัวประชาชน 13 หลัก */
				cid: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2PersonResidencyResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['M2ErrorResponse'];
				};
			};
		};
	};
	get_shelter_external_v1_shelters__code__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterDetailResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_needs_external_v1_needs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NeedsListResponse'];
				};
			};
		};
	};
	search_evacuees_external_v1_occupants_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
			/** @description Too Many Requests */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
		};
	};
	get_active_announcements_external_v1_announcements_get: {
		parameters: {
			query?: {
				/** @description Page number */
				page?: number;
				/** @description Items per page */
				size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['PaginatedAnnouncements'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_faqs_external_v1_config_faqs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ConfigResponse'];
				};
			};
		};
	};
	health_check_v1_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthCheckResponse'];
				};
			};
		};
	};
	list_needs_public_v1_needs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NeedsListResponse'];
				};
			};
		};
	};
	list_shelters_public_v1_shelters_get: {
		parameters: {
			query?: {
				province?: string | null;
				district?: string | null;
				subdistrict?: string | null;
				status?: string | null;
				site_kind?: ('evacuation_center' | 'host_house') | null;
				/** @description User latitude */
				lat?: number | null;
				/** @description User longitude */
				lng?: number | null;
				/** @description Search radius in kilometers */
				radius_km?: number | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_shelter_public_v1_shelters__code__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterDetailResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	issue_token_api_auth_token_third_party_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['TokenRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TokenResponse'];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TokenErrorResponse'];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TokenErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_clients_v1_admin_thirdparty_clients_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ThirdPartyClientListResponse'];
				};
			};
		};
	};
	create_client_v1_admin_thirdparty_clients_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['ThirdPartyClientCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ThirdPartyClientCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	revoke_client_v1_admin_thirdparty_clients__client_row_id__revoke_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				client_row_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ThirdPartyClientRevokeResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	list_locations_api_thirdparty_locations_get: {
		parameters: {
			query?: {
				/** @description Filter by location_status */
				status?: string | null;
				updated_since?: string | null;
				/** @description Include soft-deleted (is_active=false) locations */
				include_inactive?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationListEnvelope'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_location_api_thirdparty_locations__location_code__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationDetailEnvelope'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_location_occupancy_api_thirdparty_locations__location_code__occupancy_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationOccupancyEnvelope'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OccupancyErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_location_occupants_api_thirdparty_locations__location_code__occupants_get: {
		parameters: {
			query?: {
				purpose?: string | null;
			};
			header?: never;
			path: {
				location_code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OccupantsEnvelope'];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OccupantsErrorResponse'];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OccupantsErrorResponse'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['OccupantsErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_location_stock_api_thirdparty_locations__location_code__stock_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				location_code: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['LocationStockEnvelope'];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['StockErrorResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_summary_api_thirdparty_summary_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SummaryEnvelope'];
				};
			};
		};
	};
	get_transparency_summary_public_v1_transparency_summary_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['TransparencySummaryResponse'];
				};
			};
		};
	};
	create_unassigned_registration_public_v1_unassigned_registrations_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['UnassignedRegistrationCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['UnassignedRegistrationCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
