/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/v1/auth/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Verify Auth
		 * @description Verify connectivity using EXTERNAL_API_SECRET Bearer token.
		 */
		get: operations['verify_auth'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create Donation */
		post: operations['create_donation'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/donations/{tracking_token}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Donation */
		get: operations['get_donation'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/**
		 * Patch Donation Courier
		 * @description Update courier tracking on the Mongo intake buffer (pre-inbound only).
		 */
		patch: operations['patch_donation_courier'];
		trace?: never;
	};
	'/public/v1/family-search': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Search Evacuees
		 * @description Search evacuees in the public read model (masked, no PII leakage).
		 */
		post: operations['search_evacuees'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/v1/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health Check
		 * @description Health check endpoint to verify the service is running.
		 *     Returns a simple message indicating the service is healthy.
		 */
		get: operations['health_check'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/needs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Needs */
		get: operations['list_needs'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/public/v1/shelters': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Shelters
		 * @description List shelters from the MongoDB read model.
		 */
		get: operations['list_shelters'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** ApiErrorBody */
		ApiErrorBody: {
			/** Code */
			code: string;
			/** Message */
			message: string;
		};
		/** ApiErrorResponse */
		ApiErrorResponse: {
			error: components['schemas']['ApiErrorBody'];
		};
		/** DonationCourierPatchRequest */
		DonationCourierPatchRequest: {
			/** Courier Tracking No */
			courier_tracking_no: string;
		};
		/** DonationCourierPatchResponse */
		DonationCourierPatchResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/**
			 * Message
			 * @default Courier tracking number updated
			 */
			message: string;
		};
		/** DonationCreateRequest */
		DonationCreateRequest: {
			/** Shelter Code */
			shelter_code: string;
			/** Campaign Id */
			campaign_id?: string | null;
			donor: components['schemas']['DonorInput'];
			/** Items */
			items?: components['schemas']['DonationItemInput'][];
			/** Logistics */
			logistics?: {
				[key: string]: unknown;
			} | null;
			/** Captchatoken */
			captchaToken?: string | null;
		};
		/** DonationCreateResponse */
		DonationCreateResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Tracking Token */
			tracking_token: string;
			/** Booking Ref */
			booking_ref: string;
		};
		/** DonationItemInput */
		DonationItemInput: {
			/** Item Id */
			item_id?: string | null;
			/** Category */
			category?: string | null;
			/** Free Text */
			free_text?: string | null;
			/** Qty */
			qty: string | number;
			/** Unit */
			unit?: string | null;
			/** Condition */
			condition?: string | null;
			/** Note */
			note?: string | null;
		};
		/** DonationTrackingResponse */
		DonationTrackingResponse: {
			/**
			 * Success
			 * @default true
			 */
			success: boolean;
			/** Donation */
			donation: {
				[key: string]: unknown;
			};
		};
		/** DonorInput */
		DonorInput: {
			/** Name */
			name: string;
			/** Phone */
			phone: string;
			/** Line Id */
			line_id?: string | null;
			/** Email */
			email?: string | null;
		};
		/** FamilyMember */
		FamilyMember: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** Shelter Name */
			shelter_name: string;
		};
		/** GeoPoint */
		GeoPoint: {
			/** Lat */
			lat: number;
			/** Lng */
			lng: number;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Errors */
			errors?: components['schemas']['ValidationError'][];
		};
		/** HealthCheckResponse */
		HealthCheckResponse: {
			/** Status */
			status: string;
		};
		/** NeedItemResponse */
		NeedItemResponse: {
			/** Item Id */
			item_id: string;
			/** Name */
			name: string;
			/** Qty Needed */
			qty_needed: string;
			/** Unit */
			unit: string;
			/** Status */
			status: string;
		};
		/** NeedsListResponse */
		NeedsListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterNeedsResponse'][];
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** SearchRequest */
		SearchRequest: {
			/** Search */
			search: string;
		};
		/** SearchResponse */
		SearchResponse: {
			/** Results */
			results: components['schemas']['SearchResult'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** SearchResult */
		SearchResult: {
			/** Name */
			name: string;
			/** Status */
			status: string;
			/** National Id */
			national_id?: string | null;
			/** Gender */
			gender?: string | null;
			/** Shelter Name */
			shelter_name: string;
			/** Origin Address */
			origin_address?: string | null;
			/** Checked In At */
			checked_in_at?: string | null;
			/** Care Zone */
			care_zone?: string | null;
			/** Family Members */
			family_members?: components['schemas']['FamilyMember'][];
		};
		/** ShelterItem */
		ShelterItem: {
			/**
			 * Code
			 * @description Shelter code, e.g. SH001
			 */
			code: string;
			/** Name */
			name: string;
			/** Status */
			status: string;
			/**
			 * Capacity
			 * @default 0
			 */
			capacity: number;
			geo?: components['schemas']['GeoPoint'] | null;
			/** Province */
			province?: string | null;
			/** District */
			district?: string | null;
			/** Subdistrict */
			subdistrict?: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
		};
		/** ShelterListResponse */
		ShelterListResponse: {
			/** Shelters */
			shelters: components['schemas']['ShelterItem'][];
			/** Count */
			count: number;
			/**
			 * As Of
			 * Format: date-time
			 */
			as_of: string;
		};
		/** ShelterNeedsResponse */
		ShelterNeedsResponse: {
			/** Code */
			code: string;
			/** Name */
			name: string;
			/** Needs */
			needs: components['schemas']['NeedItemResponse'][];
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** VerifyResponse */
		VerifyResponse: {
			/**
			 * Status
			 * @default ok
			 */
			status: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	verify_auth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['VerifyResponse'];
				};
			};
		};
	};
	create_donation: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCreateRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCreateResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	get_donation: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationTrackingResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	patch_donation_courier: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				tracking_token: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['DonationCourierPatchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['DonationCourierPatchResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
	search_evacuees: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				'application/json': components['schemas']['SearchRequest'];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['SearchResponse'];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
			/** @description Too Many Requests */
			429: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ApiErrorResponse'];
				};
			};
		};
	};
	health_check: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HealthCheckResponse'];
				};
			};
		};
	};
	list_needs: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['NeedsListResponse'];
				};
			};
		};
	};
	list_shelters: {
		parameters: {
			query?: {
				province?: string | null;
				district?: string | null;
				subdistrict?: string | null;
				status?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['ShelterListResponse'];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': components['schemas']['HTTPValidationError'];
				};
			};
		};
	};
}
