/**
 * Server-safe facade — domain types/constants only (no Svelte UI).
 * BFF routes and `$lib/server/*` import from here so Vitest/Node never
 * resolves `.svelte` barrels. Client code continues to use the feature barrel.
 */
export {
	MASTER_DATA_TYPES,
	REGISTRATION_MASTER_TYPES,
	HOUSEHOLD_MASTER_TYPES,
	SHELTER_MASTER_TYPES,
	MASTER_DATA_TYPE_LABELS,
	MASTER_DATA_TYPE_META,
	VOLUNTEER_MASTER_TYPES,
	CR112_VULNERABLE_GROUP_ACTIVE,
	masterTypeSchema,
	masterDataSchema,
	masterDataItemSchema,
	itemInputSchema,
	enforceOneDefault,
	applyItemOp,
	createMasterData,
	touchMasterData,
	masterDocId,
	makeRegistryDoc,
	isMasterData,
	normalizeLabel,
	findDuplicateLabel,
	findLabelCollision,
	duplicateLabelKeys,
	dedupeItemsByCode,
	duplicateItemCodes,
	needsMasterDataMigration,
	migrateMasterDataToV3,
	migrateMasterDataToV4,
	normalizeMasterCode,
	isLegacyItemCode,
	formatMasterLabel,
	formatMasterLabelByCode,
	labelCollisionKey,
	type MasterDataType,
	type MasterDataTypeMeta,
	type MasterDataItem,
	type MasterLabelFields,
	type MasterLabelField,
	type MasterDataRecordScope,
	type MasterDataItemSource,
	type MasterData,
	type ItemInput,
	type ItemOp,
	type RegistryAuthorContext
} from './domain/master-data';
