/** Public API for CR-059 Flow 2 (Distribution). */

export {
	activeHeadcountSchema,
	bufferPercentSchema,
	approvalCoverageSchema,
	distributionRequestStatusSchema,
	distributionRequestItemSchema,
	distributionRequestInputSchema,
	distributionRequestDocSchema,
	validateRequestItemsDuplicateCompatibility,
	canTransitionDistributionRequest,
	calculateApprovalCoverage,
	canEditDistributionRequest,
	createDistributionRequest,
	distributionBatchStatusSchema,
	distributionBatchItemSchema,
	distributionLotSnapshotSchema,
	distributionAllocationSchema,
	distributionBatchInputSchema,
	distributionBatchDocSchema,
	canTransitionDistributionBatch,
	createDistributionBatch,
	distributionIssueIdSchema,
	distributionIssueInputSchema,
	distributionIssueDocSchema,
	createDistributionIssue,
	isDistributionIssue,
	distributionIssueIdempotencyInputSchema,
	distributionIssueIdempotencyDocSchema,
	createDistributionIssueIdempotency,
	issueCapacityPendingClaimSchema,
	distributionIssueCapacityInputSchema,
	distributionIssueCapacityDocSchema,
	createDistributionIssueCapacity,
	distributionIssueGateStateSchema,
	issueGatePendingClaimSchema,
	distributionIssueGateInputSchema,
	distributionIssueGateDocSchema,
	createDistributionIssueGate,
	oneTimeGuardPendingClaimSchema,
	distributionOneTimeGuardInputSchema,
	distributionOneTimeGuardDocSchema,
	createDistributionOneTimeGuard,
	stockLotPendingClaimSchema,
	stockLotReservationInputSchema,
	stockLotReservationDocSchema,
	createStockLotReservation,
	nfiTargetInputSchema,
	calculateNfiTarget,
	type DistributionRequestStatus,
	type ApprovalCoverage,
	type DistributionRequestItem,
	type DistributionRequestInput,
	type DistributionRequest,
	type DistributionBatchStatus,
	type DistributionBatchItem,
	type DistributionAllocation,
	type DistributionBatchInput,
	type DistributionBatch,
	type DistributionIssueInput,
	type DistributionIssue,
	type DistributionIssueIdempotencyInput,
	type DistributionIssueIdempotency,
	type IssueCapacityPendingClaim,
	type DistributionIssueCapacityInput,
	type DistributionIssueCapacity,
	type DistributionIssueGateState,
	type IssueGatePendingClaim,
	type DistributionIssueGateInput,
	type DistributionIssueGate,
	type OneTimeGuardPendingClaim,
	type DistributionOneTimeGuardInput,
	type DistributionOneTimeGuard,
	type StockLotPendingClaim,
	type StockLotReservationInput,
	type StockLotReservation,
	type NfiTargetInput
} from './domain/distribution';

export {
	distributionTypeSnapshotSchema,
	repeatOverrideReasonSchema,
	eligibilityHistoryEntrySchema,
	eligibilityInputSchema,
	eligibilitySnapshotSchema,
	evaluateDistributionEligibility,
	type DistributionTypeSnapshot,
	type RepeatOverrideReason,
	type EligibilityHistoryEntry,
	type EligibilityInput,
	type EligibilitySnapshot
} from './domain/eligibility';

export {
	reconciliationInputSchema,
	reconciliationRowSchema,
	calculateReconciliation,
	ReconciliationIntegrityError,
	closeBatchItemInputSchema,
	closeBatchInputSchema,
	type ReconciliationInput,
	type ReconciliationRow,
	type CloseBatchItemInput,
	type CloseBatchInput
} from './domain/reconciliation';
