/** Public API for CR-059 Flow 2 (Distribution). */

export {
	activeHeadcountSchema,
	bufferPercentSchema,
	approvalCoverageSchema,
	distributionRequestStatusSchema,
	distributionRequestItemSchema,
	distributionRequestInputSchema,
	distributionRequestDocSchema,
	validateRequestItemsDuplicateCompatibility,
	canTransitionDistributionRequest,
	calculateApprovalCoverage,
	canEditDistributionRequest,
	createDistributionRequest,
	distributionBatchStatusSchema,
	distributionBatchItemSchema,
	distributionLotSnapshotSchema,
	distributionAllocationSchema,
	distributionBatchInputSchema,
	distributionBatchDocSchema,
	canTransitionDistributionBatch,
	createDistributionBatch,
	distributionIssueIdSchema,
	distributionIssueInputSchema,
	distributionIssueDocSchema,
	createDistributionIssue,
	isDistributionIssue,
	distributionIssueIdempotencyInputSchema,
	distributionIssueIdempotencyDocSchema,
	createDistributionIssueIdempotency,
	issueCapacityPendingClaimSchema,
	distributionIssueCapacityInputSchema,
	distributionIssueCapacityDocSchema,
	createDistributionIssueCapacity,
	distributionIssueGateStateSchema,
	issueGatePendingClaimSchema,
	distributionIssueGateInputSchema,
	distributionIssueGateDocSchema,
	createDistributionIssueGate,
	oneTimeGuardPendingClaimSchema,
	distributionOneTimeGuardInputSchema,
	distributionOneTimeGuardDocSchema,
	createDistributionOneTimeGuard,
	stockLotPendingClaimSchema,
	stockLotReservationInputSchema,
	stockLotReservationDocSchema,
	createStockLotReservation,
	nfiTargetInputSchema,
	calculateNfiTarget,
	type DistributionRequestStatus,
	type ApprovalCoverage,
	type DistributionRequestItem,
	type DistributionRequestInput,
	type DistributionRequest,
	type DistributionBatchStatus,
	type DistributionBatchItem,
	type DistributionAllocation,
	type DistributionBatchInput,
	type DistributionBatch,
	type DistributionIssueInput,
	type DistributionIssue,
	type DistributionIssueIdempotencyInput,
	type DistributionIssueIdempotency,
	type IssueCapacityPendingClaim,
	type DistributionIssueCapacityInput,
	type DistributionIssueCapacity,
	type DistributionIssueGateState,
	type IssueGatePendingClaim,
	type DistributionIssueGateInput,
	type DistributionIssueGate,
	type OneTimeGuardPendingClaim,
	type DistributionOneTimeGuardInput,
	type DistributionOneTimeGuard,
	type StockLotPendingClaim,
	type StockLotReservationInput,
	type StockLotReservation,
	type NfiTargetInput
} from './domain/distribution';

/** Ticket-era Flow 2 domain contracts (CR-121). Legacy Flow 2 exports above remain read-compatible. */
export {
	requisitionTypeSchema,
	flow2RequisitionTypeSchema,
	requisitionTicketStatusSchema,
	mealPeriodSchema,
	ticketItemSchema,
	ticketAmendmentSchema,
	requisitionTicketInputSchema,
	requisitionTicketDocSchema,
	createFlow2RequisitionTicket,
	isFlow2RequisitionTicket,
	assertFlow2RequisitionTicket,
	canTransitionRequisitionTicket,
	assertRequisitionTicketTransition,
	assertRequisitionTicketMutation,
	distributionRecipientTypeSchema,
	distributionLogStatusSchema,
	returnConditionSchema,
	loanClearReasonSchema,
	distributionLogInputSchema,
	distributionLogDocSchema,
	createDistributionLog,
	assertDistributionLogIssuanceImmutable,
	bulkReturnPoolStatusSchema,
	bulkReturnPoolInputSchema,
	bulkReturnPoolDocSchema,
	createBulkReturnPool,
	type RequisitionType,
	type Flow2RequisitionType,
	type RequisitionTicketStatus,
	type MealPeriod,
	type TicketItem,
	type TicketAmendment,
	type RequisitionTicketInput,
	type RequisitionTicket,
	type Flow2RequisitionTicket,
	type DistributionRecipientType,
	type DistributionLogStatus,
	type DistributionLogInput,
	type DistributionLog,
	type BulkReturnPoolStatus,
	type BulkReturnPoolInput,
	type BulkReturnPool
} from './domain/food-supplies';

export {
	distributionTypeSnapshotSchema,
	repeatOverrideReasonSchema,
	eligibilityHistoryEntrySchema,
	eligibilityInputSchema,
	eligibilitySnapshotSchema,
	evaluateDistributionEligibility,
	type DistributionTypeSnapshot,
	type RepeatOverrideReason,
	type EligibilityHistoryEntry,
	type EligibilityInput,
	type EligibilitySnapshot
} from './domain/eligibility';

export {
	reconciliationInputSchema,
	reconciliationRowSchema,
	calculateReconciliation,
	ReconciliationIntegrityError,
	closeBatchItemInputSchema,
	closeBatchInputSchema,
	type ReconciliationInput,
	type ReconciliationRow,
	type CloseBatchItemInput,
	type CloseBatchInput
} from './domain/reconciliation';

export {
	type DistributionAllocationInput,
	type CreateDistributionIssueInput,
	type DistributionRecipient,
	type DistributionRepository
} from './data/distribution.repository';

export { DistributionRemoteRepository } from './data/distribution.remote';

export {
	IntegrityError,
	ApprovalConflictError,
	InsufficientStockError,
	ValidationError,
	IssueConflictError,
	IssueCapacityError,
	IssueInFlightError,
	BatchClosingConflictError,
	RecipientNotActiveError,
	DistributionEligibilityError,
	makeLotReservationDocId,
	makeIssueIdempotencyDocId,
	makeIssueCapacityDocId,
	makeIssueGateDocId,
	makeOneTimeGuardDocId,
	assertSemanticLedgerMatch,
	assertSemanticBatchMatch,
	assertSemanticReservationMatch,
	assertSemanticIdempotencyMatch,
	assertEligibilitySnapshotInvariant,
	assertSemanticIssueMatch,
	assertSemanticClosingMatch
} from './data/semantic-verify';

/** Ticket-era Flow 2 persistence repositories (CR-121). Legacy DistributionRemoteRepository above remains intact. */
export {
	RequisitionTicketRemoteRepository,
	DistributionLogRemoteRepository,
	BulkReturnPoolRemoteRepository,
	type RequisitionTicketRepository,
	type RequisitionTicketListFilter,
	type RequisitionTicketTransitionPatch,
	type DistributionLogRepository,
	type DistributionLogListFilter,
	type RecordReturnInput,
	type RecordClearInput,
	type BulkReturnPoolRepository,
	type BulkReturnPoolListFilter
} from './data/food-supplies';
