/**
 * Shared CouchDB / BFF route mocks for the evacuee-registration E2E suites
 * (`register-evacuee.test.ts` and `register-evacuee-full.test.ts`).
 *
 * Keeps tests self-contained — no real CouchDB data is mutated.
 * Skill note: "Avoid mocking where possible" — we only mock the DB/BFF layer;
 * the full SvelteKit BFF and Svelte UI run against the real preview server.
 */

import type { Page } from '@playwright/test';

/** A `shelter:SH001` role resolves to this CouchDB database (db/shelter.ts). */
export const SHELTER_DB = 'shelter_sh001';

/** One shelter (SH001) with one open zone — enough for step 6's zone recommendation. */
const REGISTRY_SHELTER_SH001 = {
	_id: 'shelter:SH001',
	_rev: '1-mock',
	type: 'shelter',
	schema_v: 4,
	code: 'SH001',
	name: 'ศูนย์พักพิง E2E',
	operation_status: 'active',
	capacity: 100,
	zones: [
		{
			code: 'A',
			name: 'โซน A (ทั่วไป)',
			capacity: 50,
			type: 'general',
			status: 'active'
		}
	],
	admission_policy: {
		supported_vulnerable_groups: [],
		pet_policy: { policy: null, categories: [] }
	},
	luggage_policy: {
		limitation: null,
		max_per_family: null,
		rules: [],
		rules_other: null
	},
	parking_policy: {
		availability: null,
		supported_vehicles: [],
		rules: [],
		rules_other: null
	}
};

export interface MockCouchRoutesOptions {
	/**
	 * Also mock `registry/_all_docs` with the SH001 shelter fixture — needed by
	 * flows that reach step 6 (zone recommendation/selection via useShelter()).
	 */
	withRegistryShelter?: boolean;
}

/**
 * Mount all CouchDB / BFF route mocks needed by the registration wizard.
 * Register BEFORE any navigation. Individual tests may override single routes
 * afterwards — Playwright matches the last-registered route first.
 */
export async function mockCouchRoutes(
	page: Page,
	{ withRegistryShelter = false }: MockCouchRoutesOptions = {}
): Promise<void> {
	// CouchDB _changes (live-sync) — return empty immediately to avoid timeouts
	await page.route('**/_changes**', async (route) => {
		await route.fulfill({
			status: 200,
			contentType: 'application/json',
			body: JSON.stringify({ results: [], last_seq: '0' })
		});
	});

	// Mango _find (search) — default: return empty list (no prior registrations)
	await page.route('**/_find**', async (route) => {
		await route.fulfill({
			status: 200,
			contentType: 'application/json',
			body: JSON.stringify({ docs: [], bookmark: 'nil' })
		});
	});

	// CouchDB _all_docs — searchEvacuees()/listEvacuees()/listHouseholds() scan by
	// type prefix via _all_docs (not _find); default to an empty result set so
	// search/household flows reliably fall into the "not found" path.
	await page.route('**/_all_docs**', async (route) => {
		await route.fulfill({
			status: 200,
			contentType: 'application/json',
			body: JSON.stringify({ rows: [] })
		});
	});

	// Shelter registry — useShelter() scans the `registry` db's _all_docs for
	// `shelter:*` docs (not a BFF route). Registered after the generic _all_docs
	// mock above so it takes precedence for this path.
	if (withRegistryShelter) {
		await page.route('**/registry/_all_docs**', async (route) => {
			await route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify({
					rows: [{ id: REGISTRY_SHELTER_SH001._id, doc: REGISTRY_SHELTER_SH001 }]
				})
			});
		});
	}

	// Shelter DB (evacuee/household/movement/medical/screening docs) — a tiny
	// in-memory doc store so the GET-after-PUT rev lookups used throughout the
	// flow (updateEvacuee, checkInEvacuee, …) resolve against what was actually
	// written, instead of a fixed canned response. Doc ids are ULID-based
	// (generated by makeDoc), so the store keys off the real request path.
	const docs = new Map<string, Record<string, unknown>>();
	let revCounter = 0;
	await page.route(`**/${SHELTER_DB}/**`, async (route) => {
		const req = route.request();
		const segments = new URL(req.url()).pathname.split('/').filter(Boolean);
		const last = segments[segments.length - 1] ?? '';
		if (last.startsWith('_')) {
			// Not a single-doc path (_all_docs, _find, _changes, …) — defer to
			// the generic mocks registered above.
			await route.fallback();
			return;
		}

		const docId = decodeURIComponent(last);
		if (req.method() === 'GET') {
			const doc = docs.get(docId);
			if (doc) {
				await route.fulfill({
					status: 200,
					contentType: 'application/json',
					body: JSON.stringify(doc)
				});
			} else {
				await route.fulfill({
					status: 404,
					contentType: 'application/json',
					body: JSON.stringify({ error: 'not_found', reason: 'missing' })
				});
			}
			return;
		}
		if (req.method() === 'PUT') {
			const body = (req.postDataJSON() ?? {}) as Record<string, unknown>;
			const isCreate = !docs.has(docId);
			revCounter += 1;
			const rev = `${revCounter}-mock`;
			docs.set(docId, { ...body, _id: docId, _rev: rev });
			await route.fulfill({
				status: isCreate ? 201 : 200,
				contentType: 'application/json',
				body: JSON.stringify({ ok: true, id: docId, rev })
			});
			return;
		}
		await route.fallback();
	});

	// BFF catch-all with special-cases inside (Playwright matches last-registered
	// route first — separate specific /api routes registered *after* this would
	// never run if we registered a blanket /api/** last).
	await page.route('/api/**', async (route) => {
		const url = route.request().url();
		if (url.includes('/api/v1/thailand-location/all')) {
			await route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify([
					{ province: 'สงขลา', district: 'หาดใหญ่', subdistrict: 'บ้านพรุ', zipcode: 90250 }
				])
			});
			return;
		}
		if (url.includes('/api/back-office/master-data/vulnerable_group')) {
			await route.fulfill({
				status: 200,
				contentType: 'application/json',
				body: JSON.stringify({
					_id: 'master_data:vulnerable_group',
					master_type: 'vulnerable_group',
					items: []
				})
			});
			return;
		}
		await route.fulfill({
			status: 200,
			contentType: 'application/json',
			body: JSON.stringify({ ok: true })
		});
	});
}
