export interface Country {
	value: string;
	label: string;
}

export const COUNTRIES: Country[] = [
	{ value: 'THAILAND', label: 'ไทย' },
	{ value: 'GREECE', label: 'กรีซ' },
	{ value: 'GREENLAND', label: 'กรีนแลนด์' },
	{ value: 'GUAM', label: 'กวม' },
	{ value: 'CAMBODIA', label: 'กัมพูชา' },
	{ value: 'GUADELOUPE', label: 'กัวเดอลุป' },
	{ value: 'GUATEMALA', label: 'กัวเตมาลา' },
	{ value: 'QATAR', label: 'กาตาร์' },
	{ value: 'GHANA', label: 'กานา' },
	{ value: 'GABON', label: 'กาบอง' },
	{ value: 'CABO VERDE', label: 'กาบูเวร์ดี' },
	{ value: 'GUYANA', label: 'กายอานา' },
	{ value: 'GUINEA', label: 'กินี' },
	{ value: 'GUINEA-BISSAU', label: 'กินี-บิสเซา' },
	{ value: 'CURAÇAO', label: 'กือราเซา' },
	{ value: 'COSTA RICA', label: 'คอสตาริกา' },
	{ value: 'COMOROS', label: 'คอโมโรส' },
	{ value: 'KAZAKHSTAN', label: 'คาซัคสถาน' },
	{ value: 'KIRIBATI', label: 'คิริบาส' },
	{ value: 'CUBA', label: 'คิวบา' },
	{ value: 'KYRGYZSTAN', label: 'คีร์กีซสถาน' },
	{ value: 'KUWAIT', label: 'คูเวต' },
	{ value: 'GEORGIA', label: 'จอร์เจีย' },
	{ value: 'JORDAN', label: 'จอร์แดน' },
	{ value: 'JAMAICA', label: 'จาเมกา' },
	{ value: 'DJIBOUTI', label: 'จิบูตี' },
	{ value: 'CHINA', label: 'จีน' },
	{ value: 'CHAD', label: 'ชาด' },
	{ value: 'CHILE', label: 'ชิลี' },
	{ value: 'SAN MARINO', label: 'ซานมารีโน' },
	{ value: 'SAMOA', label: 'ซามัว' },
	{ value: 'SAUDI ARABIA', label: 'ซาอุดีอาระเบีย' },
	{ value: 'WESTERN SAHARA', label: 'ซาฮาราตะวันตก' },
	{ value: 'SINT MAARTEN', label: 'ซินต์มาร์เติน' },
	{ value: 'ZIMBABWE', label: 'ซิมบับเว' },
	{ value: 'SYRIAN ARAB REPUBLIC', label: 'ซีเรีย' },
	{ value: 'SUDAN', label: 'ซูดาน' },
	{ value: 'SURINAME', label: 'ซูรินาม' },
	{ value: 'JAPAN', label: 'ญี่ปุ่น' },
	{ value: 'DOMINICA', label: 'ดอมินีกา' },
	{ value: 'TRINIDAD AND TOBAGO', label: 'ตรินิแดดและโตเบโก' },
	{ value: 'TONGA', label: 'ตองงา' },
	{ value: 'TIMOR-LESTE', label: 'ติมอร์-เลสเต' },
	{ value: 'TURKEY', label: 'ตุรกี' },
	{ value: 'TUNISIA', label: 'ตูนิเซีย' },
	{ value: 'TUVALU', label: 'ตูวาลู' },
	{ value: 'TAJIKISTAN', label: 'ทาจิกิสถาน' },
	{ value: 'VATICAN CITY STATE', label: 'นครรัฐวาติกัน' },
	{ value: 'NORTH MACEDONIA', label: 'นอร์ทมาซิโดเนีย' },
	{ value: 'NORWAY', label: 'นอร์เวย์' },
	{ value: 'NAMIBIA', label: 'นามิเบีย' },
	{ value: 'NAURU', label: 'นาอูรู' },
	{ value: 'NICARAGUA', label: 'นิการากัว' },
	{ value: 'NEW ZEALAND', label: 'นิวซีแลนด์' },
	{ value: 'NEW CALEDONIA', label: 'นิวแคลิโดเนีย' },
	{ value: 'NIUE', label: 'นีวเว' },
	{ value: 'BRAZIL', label: 'บราซิล' },
	{ value: 'BRITISH INDIAN OCEAN TERRITORY', label: 'บริติชอินเดียนโอเชียนเทร์ริทอรี' },
	{ value: 'BRUNEI DARUSSALAM', label: 'บรูไน' },
	{ value: 'BOTSWANA', label: 'บอตสวานา' },
	{ value: 'BOSNIA AND HERZEGOVINA', label: 'บอสเนียและเฮอร์เซโกวีนา' },
	{ value: 'BANGLADESH', label: 'บังกลาเทศ' },
	{ value: 'BULGARIA', label: 'บัลแกเรีย' },
	{ value: 'BARBADOS', label: 'บาร์เบโดส' },
	{ value: 'BAHRAIN', label: 'บาห์เรน' },
	{ value: 'BAHAMAS', label: 'บาฮามาส' },
	{ value: 'BURUNDI', label: 'บุรุนดี' },
	{ value: 'BURKINA FASO', label: 'บูร์กินาฟาโซ' },
	{ value: 'PUERTO RICO', label: 'ปวยร์โตรีโก' },
	{ value: 'PAKISTAN', label: 'ปากีสถาน' },
	{ value: 'PANAMA', label: 'ปานามา' },
	{ value: 'PAPUA NEW GUINEA', label: 'ปาปัวนิวกินี' },
	{ value: 'PARAGUAY', label: 'ปารากวัย' },
	{ value: 'PALESTINE', label: 'ปาเลสไตน์' },
	{ value: 'PALAU', label: 'ปาเลา' },
	{ value: 'FRANCE', label: 'ฝรั่งเศส' },
	{ value: 'MYANMAR', label: 'พม่า' },
	{ value: 'FINLAND', label: 'ฟินแลนด์' },
	{ value: 'PHILIPPINES', label: 'ฟิลิปปินส์' },
	{ value: 'FIJI', label: 'ฟีจี' },
	{ value: 'BHUTAN', label: 'ภูฏาน' },
	{ value: 'MONGOLIA', label: 'มองโกเลีย' },
	{ value: 'MONTSERRAT', label: 'มอนต์เซอร์รัต' },
	{ value: 'MONTENEGRO', label: 'มอนเตเนโกร' },
	{ value: 'MAURITIUS', label: 'มอริเชียส' },
	{ value: 'MAURITANIA', label: 'มอริเตเนีย' },
	{ value: 'MALTA', label: 'มอลตา' },
	{ value: 'MOLDOVA', label: 'มอลโดวา' },
	{ value: 'MALDIVES', label: 'มัลดีฟส์' },
	{ value: 'MADAGASCAR', label: 'มาดากัสการ์' },
	{ value: 'MAYOTTE', label: 'มายอต' },
	{ value: 'MARTINIQUE', label: 'มาร์ตีนิก' },
	{ value: 'MALAWI', label: 'มาลาวี' },
	{ value: 'MALI', label: 'มาลี' },
	{ value: 'MACAO', label: 'มาเก๊า' },
	{ value: 'MALAYSIA', label: 'มาเลเซีย' },
	{ value: 'GIBRALTAR', label: 'ยิบรอลตาร์' },
	{ value: 'UGANDA', label: 'ยูกันดา' },
	{ value: 'UKRAINE', label: 'ยูเครน' },
	{ value: 'RWANDA', label: 'รวันดา' },
	{ value: 'RUSSIAN FEDERATION', label: 'รัสเซีย' },
	{ value: 'LUXEMBOURG', label: 'ลักเซมเบิร์ก' },
	{ value: 'LATVIA', label: 'ลัตเวีย' },
	{ value: 'LAOS', label: 'ลาว' },
	{ value: 'LIECHTENSTEIN', label: 'ลิกเตนสไตน์' },
	{ value: 'LITHUANIA', label: 'ลิทัวเนีย' },
	{ value: 'LIBYA', label: 'ลิเบีย' },
	{ value: 'VANUATU', label: 'วานูวาตู' },
	{ value: 'WALLIS AND FUTUNA', label: 'วาลิสและฟูตูนา' },
	{ value: 'SRI LANKA', label: 'ศรีลังกา' },
	{ value: 'SVALBARD AND JAN MAYEN', label: 'สฟาลบาร์และยานไมเอน' },
	{ value: 'SWAZILAND', label: 'สวาซิแลนด์' },
	{ value: 'SWITZERLAND', label: 'สวิตเซอร์แลนด์' },
	{ value: 'SWEDEN', label: 'สวีเดน' },
	{ value: 'UNITED STATES OF AMERICA', label: 'สหรัฐ' },
	{ value: 'UNITED ARAB EMIRATES', label: 'สหรัฐอาหรับเอมิเรตส์' },
	{ value: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND', label: 'สหราชอาณาจักร' },
	{ value: 'REPUBLIC OF THE CONGO', label: 'สาธารณรัฐคองโก' },
	{ value: 'DEMOCRATIC REPUBLIC OF THE CONGO', label: 'สาธารณรัฐประชาธิปไตยคองโก' },
	{ value: 'CENTRAL AFRICAN REPUBLIC', label: 'สาธารณรัฐแอฟริกากลาง' },
	{ value: 'DOMINICAN REPUBLIC', label: 'สาธารณรัฐโดมินิกัน' },
	{ value: 'SINGAPORE', label: 'สิงคโปร์' },
	{ value: 'SPAIN', label: 'สเปน' },
	{ value: 'SLOVAKIA', label: 'สโลวาเกีย' },
	{ value: 'SLOVENIA', label: 'สโลวีเนีย' },
	{ value: 'COOK ISLANDS', label: 'หมู่เกาะคุก' },
	{ value: 'NORTHERN MARIANA ISLANDS', label: 'หมู่เกาะนอร์เทิร์นมาเรียนา' },
	{ value: 'BRITISH VIRGIN ISLANDS', label: 'หมู่เกาะบริติชเวอร์จิน' },
	{ value: 'PITCAIRN', label: 'หมู่เกาะพิตแคร์น' },
	{ value: 'FALKLAND ISLANDS', label: 'หมู่เกาะฟอล์กแลนด์' },
	{ value: 'MARSHALL ISLANDS', label: 'หมู่เกาะมาร์แชลล์' },
	{ value: 'CAYMAN ISLANDS', label: 'หมู่เกาะเคย์แมน' },
	{ value: 'TURKS AND CAICOS ISLANDS', label: 'หมู่เกาะเติกส์และเคคอส' },
	{ value: 'UNITED STATES VIRGIN ISLANDS', label: 'หมู่เกาะเวอร์จินของสหรัฐอเมริกา' },
	{ value: 'FAROE ISLANDS', label: 'หมู่เกาะแฟโร' },
	{ value: 'COCOS (KEELING) ISLANDS', label: 'หมู่เกาะโคโคส' },
	{ value: 'SOLOMON ISLANDS', label: 'หมู่เกาะโซโลมอน' },
	{ value: 'ÅLAND ISLANDS', label: 'หมู่เกาะโอลันด์' },
	{ value: 'AUSTRIA', label: 'ออสเตรีย' },
	{ value: 'AUSTRALIA', label: 'ออสเตรเลีย' },
	{ value: 'ANDORRA', label: 'อันดอร์รา' },
	{ value: 'AFGHANISTAN', label: 'อัฟกานิสถาน' },
	{ value: 'ARUBA', label: 'อารูบา' },
	{ value: 'ARMENIA', label: 'อาร์มีเนีย' },
	{ value: 'ARGENTINA', label: 'อาร์เจนตินา' },
	{ value: 'AZERBAIJAN', label: 'อาเซอร์ไบจาน' },
	{ value: 'ITALY', label: 'อิตาลี' },
	{ value: 'INDIA', label: 'อินเดีย' },
	{ value: 'INDONESIA', label: 'อินโดนีเซีย' },
	{ value: 'IRAQ', label: 'อิรัก' },
	{ value: 'ISRAEL', label: 'อิสราเอล' },
	{ value: 'IRAN', label: 'อิหร่าน' },
	{ value: 'EQUATORIAL GUINEA', label: 'อิเควทอเรียลกินี' },
	{ value: 'EGYPT', label: 'อียิปต์' },
	{ value: 'UZBEKISTAN', label: 'อุซเบกิสถาน' },
	{ value: 'URUGUAY', label: 'อุรุกวัย' },
	{ value: 'AMERICAN SAMOA', label: 'อเมริกันซามัว' },
	{ value: 'HONDURAS', label: 'ฮอนดูรัส' },
	{ value: 'HUNGARY', label: 'ฮังการี' },
	{ value: 'HONG KONG', label: 'ฮ่องกง' },
	{ value: 'GRENADA', label: 'เกรเนดา' },
	{ value: 'NORTH KOREA', label: 'เกาหลีเหนือ' },
	{ value: 'SOUTH KOREA', label: 'เกาหลีใต้' },
	{ value: 'CHRISTMAS ISLAND', label: 'เกาะคริสต์มาส' },
	{ value: 'NORFOLK ISLAND', label: 'เกาะนอร์ฟอล์ก' },
	{ value: 'BOUVET ISLAND', label: 'เกาะบูเวต์' },
	{ value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', label: 'เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช' },
	{ value: 'SOUTH SUDAN', label: 'เกาะเซาท์จอร์เจียและหมู่เกาะเซาท์แซนด์วิช' },
	{ value: 'UNITED STATES MINOR OUTLYING ISLANDS', label: 'เกาะเล็กรอบนอกของสหรัฐอเมริกา' },
	{ value: 'HEARD ISLAND AND MCDONALD ISLANDS', label: 'เกาะเฮิร์ดและหมู่เกาะแมกดอนัลด์' },
	{ value: 'GUERNSEY', label: 'เกิร์นซีย์' },
	{ value: 'KENYA', label: 'เคนยา' },
	{ value: 'JERSEY', label: 'เจอร์ซีย์' },
	{ value: 'CZECH REPUBLIC', label: 'เช็กเกีย' },
	{ value: 'SAINT KITTS AND NEVIS', label: 'เซนต์คิตส์และเนวิส' },
	{ value: 'SAINT LUCIA', label: 'เซนต์ลูเชีย' },
	{ value: 'SAINT VINCENT AND THE GRENADINES', label: 'เซนต์วินเซนต์และเกรนาดีนส์' },
	{ value: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA', label: 'เซนต์เฮเลนา' },
	{ value: 'SERBIA', label: 'เซอร์เบีย' },
	{ value: 'SAO TOME AND PRINCIPE', label: 'เซาตูเมและปรินซีปี' },
	{ value: 'SIERRA LEONE', label: 'เซียร์ราลีโอน' },
	{ value: 'SEYCHELLES', label: 'เซเชลส์' },
	{ value: 'SENEGAL', label: 'เซเนกัล' },
	{ value: 'DENMARK', label: 'เดนมาร์ก' },
	{ value: 'TURKMENISTAN', label: 'เติร์กเมนิสถาน' },
	{ value: 'NEPAL', label: 'เนปาล' },
	{ value: 'NETHERLANDS', label: 'เนเธอร์แลนด์' },
	{ value: 'BONAIRE, SINT EUSTATIUS AND SABA', label: 'เนเธอร์แลนด์แคริบเบียน' },
	{ value: 'BENIN', label: 'เบนิน' },
	{ value: 'BELARUS', label: 'เบลารุส' },
	{ value: 'BELIZE', label: 'เบลีซ' },
	{ value: 'BELGIUM', label: 'เบลเยียม' },
	{ value: 'BERMUDA', label: 'เบอร์มิวดา' },
	{ value: 'PERU', label: 'เปรู' },
	{ value: 'FRENCH POLYNESIA', label: 'เฟรนช์พอลินีเชีย' },
	{ value: 'FRENCH GUIANA', label: 'เฟรนช์เกียนา' },
	{ value: 'FRENCH SOUTHERN TERRITORIES', label: 'เฟรนช์เซาเทิร์นและแอนตาร์กติกแลนดส์' },
	{ value: 'MEXICO', label: 'เม็กซิโก' },
	{ value: 'GERMANY', label: 'เยอรมนี' },
	{ value: 'YEMEN', label: 'เยเมน' },
	{ value: 'RÉUNION', label: 'เรอูว์นียง' },
	{ value: 'LEBANON', label: 'เลบานอน' },
	{ value: 'LESOTHO', label: 'เลโซโท' },
	{ value: 'VIETNAM', label: 'เวียดนาม' },
	{ value: 'VENEZUELA', label: 'เวเนซุเอลา' },
	{ value: 'ECUADOR', label: 'เอกวาดอร์' },
	{ value: 'ETHIOPIA', label: 'เอธิโอเปีย' },
	{ value: 'ERITREA', label: 'เอริเทรีย' },
	{ value: 'EL SALVADOR', label: 'เอลซัลวาดอร์' },
	{ value: 'ESTONIA', label: 'เอสโตเนีย' },
	{ value: 'HAITI', label: 'เฮติ' },
	{ value: 'GAMBIA', label: 'แกมเบีย' },
	{ value: 'CANADA', label: 'แคนาดา' },
	{ value: 'CAMEROON', label: 'แคเมอรูน' },
	{ value: 'SAINT BARTHÉLEMY', label: 'แซงบาร์เตเลมี' },
	{ value: 'SAINT PIERRE AND MIQUELON', label: 'แซงปีแยร์และมีเกอลง' },
	{ value: 'SAINT MARTIN', label: 'แซงมาร์แตง' },
	{ value: 'ZAMBIA', label: 'แซมเบีย' },
	{ value: 'TANZANIA', label: 'แทนซาเนีย' },
	{ value: 'ANGUILLA', label: 'แองกวิลลา' },
	{ value: 'ANGOLA', label: 'แองโกลา' },
	{ value: 'ANTARCTICA', label: 'แอนตาร์กติกา' },
	{ value: 'ANTIGUA AND BARBUDA', label: 'แอนติกาและบาร์บูดา' },
	{ value: 'SOUTH AFRICA', label: 'แอฟริกาใต้' },
	{ value: 'ALGERIA', label: 'แอลจีเรีย' },
	{ value: 'ALBANIA', label: 'แอลเบเนีย' },
	{ value: 'CÔTE D\'IVOIRE', label: 'โกตดิวัวร์' },
	{ value: 'CROATIA', label: 'โครเอเชีย' },
	{ value: 'COLOMBIA', label: 'โคลอมเบีย' },
	{ value: 'SOMALIA', label: 'โซมาเลีย' },
	{ value: 'TOGO', label: 'โตโก' },
	{ value: 'TOKELAU', label: 'โทเคอเลา' },
	{ value: 'BOLIVIA', label: 'โบลิเวีย' },
	{ value: 'PORTUGAL', label: 'โปรตุเกส' },
	{ value: 'POLAND', label: 'โปแลนด์' },
	{ value: 'MOZAMBIQUE', label: 'โมซัมบิก' },
	{ value: 'MONACO', label: 'โมนาโก' },
	{ value: 'MOROCCO', label: 'โมร็อกโก' },
	{ value: 'ROMANIA', label: 'โรมาเนีย' },
	{ value: 'OMAN', label: 'โอมาน' },
	{ value: 'CYPRUS', label: 'ไซปรัส' },
	{ value: 'TAIWAN', label: 'ไต้หวัน' },
	{ value: 'NIGERIA', label: 'ไนจีเรีย' },
	{ value: 'NIGER', label: 'ไนเจอร์' },
	{ value: 'MICRONESIA', label: 'ไมโครนีเซีย' },
	{ value: 'LIBERIA', label: 'ไลบีเรีย' },
	{ value: 'ICELAND', label: 'ไอซ์แลนด์' },
	{ value: 'IRELAND', label: 'ไอร์แลนด์' },
	{ value: 'ISLE OF MAN', label: 'ไอล์ออฟแมน' },
	{ value: 'OTHER', label: 'อื่นๆ' },
];
